In [1]:
import gc
import json
import math
import os
import random
import re
import time
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import DatasetDict, load_dataset
from torch.utils.data import DataLoader
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

print('Python/PyTorch ready')
print('PyTorch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('GPU count:', torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(i, torch.cuda.get_device_name(i))

/mnt/mydisk/bigdata_a1/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Python/PyTorch ready
PyTorch: 2.6.0+cu124
CUDA available: True
GPU count: 1
0 NVIDIA RTX A6000

In [2]:
# Outside Kaggle, set A1_RESULT_ROOT to a writable folder (defaults to the Kaggle path).
RESULT_ROOT = Path(os.environ.get('A1_RESULT_ROOT', '/kaggle/working/Assignment1'))
RESULT_ROOT.mkdir(parents=True, exist_ok=True)

MODEL_ID = os.environ.get('A1_MODEL_ID', 'meta-llama/Llama-3.2-1B')
MODEL_DTYPE = torch.float16
TRAIN_DEVICE = torch.device('cuda:0')
SVD_DEVICE = torch.device('cuda:0')

METAMATH_TRAIN_LIMIT = 25000
METAMATH_TRAIN_DATASET_ID = 'meta-math/MetaMathQA'

PISSA_EVAL_DATASET_ID = 'fxmeng/pissa-dataset'
PISSA_EVAL_DATA_DIR = 'metamath'
EVAL_TASKS = ['gsm8k', 'math']

MAX_LENGTH = 512
EPOCHS = 1
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.0
WARMUP_RATIO = 0.03
TARGET_GLOBAL_BATCH = 128

MICRO_BATCH_SIZE = 8
USE_DATA_PARALLEL = torch.cuda.device_count() >= 2
GRAD_ACCUM_STEPS = max(1, TARGET_GLOBAL_BATCH // MICRO_BATCH_SIZE)

EVAL_MAX_NEW_TOKENS = 256
EVAL_BATCH_SIZE = 4

# Save individual prediction JSONL files. Disable to reduce disk usage.
SAVE_PREDICTIONS = True
SAVE_ADAPTERS = True
SAVE_FULL_MODEL = True


# ========================================================================================================================
# TODO for Question 1
"""
`MANUAL_RUNS` is used to configure the SVD settings for fine-tuning the LLM.
   - 'rank': the target rank used for truncated SVD
   - 'component': the selected range of singular values, corresponding to the settings in Question 3
"""
MANUAL_RUNS = [
   # Question 1: top singular values ('default') at three target ranks
   {'rank': 16, 'component': 'default'},
   {'rank': 64, 'component': 'default'},
   {'rank': 256, 'component': 'default'},
   # Question 3: rank 16 taken from other parts of the singular-value spectrum
   {'rank': 16, 'component': 'q25'},     # 16 consecutive values starting at the 25% position
   {'rank': 16, 'component': 'q50'},     # 16 consecutive values starting at the 50% position
   {'rank': 16, 'component': 'bottom'},  # the smallest 16 singular values
]
# Optional: run a subset (e.g. one run per GPU) by passing JSON in A1_RUNS.
if os.environ.get('A1_RUNS'):
    MANUAL_RUNS = json.loads(os.environ['A1_RUNS'])

"""
`RUN_FRESH_BASELINE` is used to evaluate the original LLM without fine-tuning.
   - True: runs the original LLM as the baseline.
   - False: skips the baseline evaluation.
"""
RUN_FRESH_BASELINE = os.environ.get('A1_RUN_BASELINE', '1') == '1'
# ========================================================================================================================

assert TARGET_GLOBAL_BATCH % MICRO_BATCH_SIZE == 0
print('Effective batch:', MICRO_BATCH_SIZE * GRAD_ACCUM_STEPS)
print('MetaMathQA train limit:', METAMATH_TRAIN_LIMIT)
print('Evaluation tasks:', EVAL_TASKS)
print('Results:', RESULT_ROOT)

Effective batch: 128
MetaMathQA train limit: 25000
Evaluation tasks: ['gsm8k', 'math']
Results: /mnt/mydisk/bigdata_a1/results/baseline

In [3]:
# Llama-3.2 is gated. On Kaggle, store a secret named HF_TOKEN; elsewhere, export HF_TOKEN or use `hf auth login`.
from huggingface_hub import login

try:
    from kaggle_secrets import UserSecretsClient
    token = UserSecretsClient().get_secret('HF_TOKEN')
except Exception:
    token = os.environ.get('HF_TOKEN')

if token:
    login(token=token)
    print('Hugging Face login: OK')
else:
    print('No HF_TOKEN found; using the cached Hugging Face login.')

No HF_TOKEN found; using the cached Hugging Face login.

In [4]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.model_max_length = MAX_LENGTH

IGNORE_INDEX = -100
PISSA_PROMPT = (
    'Below is an instruction that describes a task. '
    'Write a response that appropriately completes the request.\n\n'
    '### Instruction:\n{instruction}\n\n### Response:'
)

print('Tokenizer:', MODEL_ID)
print('EOS:', tokenizer.eos_token_id, 'PAD:', tokenizer.pad_token_id)

Tokenizer: meta-llama/Llama-3.2-1B
EOS: 128001 PAD: 128001

In [5]:
def load_metamathqa_train_like_pissa():
    """Load MetaMathQA directly and convert query/response to PiSSA's instruction/output schema."""
    split = (
        'train'
        if METAMATH_TRAIN_LIMIT is None
        else f'train[:{METAMATH_TRAIN_LIMIT}]'
    )
    train = load_dataset(
        METAMATH_TRAIN_DATASET_ID,
        split=split,
    )

    train = train.map(
        lambda x: {
            'instruction': str(x['query']).strip(),
            'output': str(x['response']).strip(),
            'source_type': str(x.get('type', '')),
        },
        remove_columns=train.column_names,
        desc='Formatting MetaMathQA for PiSSA training',
    )
    return train


def load_pissa_metamath_eval():
    """Load GSM8K and MATH from PiSSA's original Hugging Face metamath test split."""
    raw_test = load_dataset(
        PISSA_EVAL_DATASET_ID,
        data_dir=PISSA_EVAL_DATA_DIR,
        split='test',
    )

    eval_sets = {}
    normalized_types = [str(x).lower() for x in raw_test['type']]

    for task in EVAL_TASKS:
        keep_indices = [
            i for i, task_type in enumerate(normalized_types)
            if task_type == task
        ]
        subset = raw_test.select(keep_indices)
        if len(subset) == 0:
            raise RuntimeError(
                f'No {task!r} rows found in '
                f'{PISSA_EVAL_DATASET_ID}/{PISSA_EVAL_DATA_DIR} test split.'
            )

        # PiSSA gen_vllm.py generates from "instruction" and passes "output"
        # unchanged to test_acc.py as the gold answer.
        subset = subset.map(
            lambda x: {
                'instruction': str(x['instruction']),
                'gold_answer': str(x['output']),
                'type': str(x['type']).lower(),
            },
            remove_columns=subset.column_names,
            desc=f'Formatting PiSSA {task} evaluation set',
        )
        eval_sets[task] = subset

    return eval_sets

In [6]:
# Load once; all PiSSA ranks/components reuse exactly the same training and test rows.
TRAIN_DATASET = load_metamathqa_train_like_pissa()
EVAL_DATASETS = load_pissa_metamath_eval()

print('\nTRAIN:', TRAIN_DATASET)
print('train example:', TRAIN_DATASET[0])

for task, ds in EVAL_DATASETS.items():
    print(f'\nEVAL {task}:', ds)
    print('test example:', ds[0])

TRAIN: Dataset({
    features: ['instruction', 'output', 'source_type'],
    num_rows: 25000
})
train example: {'instruction': "Gracie and Joe are choosing numbers on the complex plane. Joe chooses the point $1+2i$. Gracie chooses $-1+i$. How far apart are Gracie and Joe's points?", 'output': "The distance between two points $(x_1,y_1)$ and $(x_2,y_2)$ in the complex plane is given by the formula $\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$.\nIn this case, Joe's point is $(1,2)$ and Gracie's point is $(-1,1)$.\nSo the distance between their points is $\\sqrt{((-1)-(1))^2+((1)-(2))^2}=\\sqrt{(-2)^2+(-1)^2}=\\sqrt{4+1}=\\sqrt{5}$.\nTherefore, Gracie and Joe's points are $\\boxed{\\sqrt{5}}$ units apart.\nThe answer is: \\sqrt{5}", 'source_type': 'MATH_AnsAug'}

EVAL gsm8k: Dataset({
    features: ['instruction', 'type', 'gold_answer'],
    num_rows: 1319
})
test example: {'instruction': "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nJanet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?\n\n### Response: Let's think step by step.", 'type': 'gsm8k', 'gold_answer': '18'}

EVAL math: Dataset({
    features: ['instruction', 'type', 'gold_answer'],
    num_rows: 5000
})
test example: {'instruction': "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nFind the matrix $\\mathbf{M}$ such that\n\\[\\mathbf{M} \\begin{pmatrix} 1 & -2 \\\\ 1 & 4 \\end{pmatrix} = \\begin{pmatrix} 6 & 0 \\\\ 0 & 6 \\end{pmatrix}.\\]\n\n### Response: Let's think step by step.", 'type': 'math', 'gold_answer': '\\begin{pmatrix} 4 & 2 \\\\ -1 & 1 \\end{pmatrix}'}

In [7]:
def tokenize_supervised_example(example):
    source = PISSA_PROMPT.format(instruction=example['instruction'])
    target = f"{example['output']}\n{tokenizer.eos_token}"

    full = tokenizer(
        source + target,
        max_length=MAX_LENGTH,
        truncation=True,
        add_special_tokens=True,
    )
    source_tok = tokenizer(
        source,
        max_length=MAX_LENGTH,
        truncation=True,
        add_special_tokens=True,
    )

    input_ids = full['input_ids']
    labels = input_ids.copy()
    source_len = min(len(source_tok['input_ids']), len(labels))
    labels[:source_len] = [IGNORE_INDEX] * source_len

    return {
        'input_ids': input_ids,
        'labels': labels,
        'supervised_tokens': sum(v != IGNORE_INDEX for v in labels),
    }


@dataclass
class ResponseOnlyCollator:
    pad_token_id: int

    def __call__(self, features):
        max_len = max(len(x['input_ids']) for x in features)
        input_ids, labels, attention_mask = [], [], []

        for x in features:
            n_pad = max_len - len(x['input_ids'])
            input_ids.append(x['input_ids'] + [self.pad_token_id] * n_pad)
            labels.append(x['labels'] + [IGNORE_INDEX] * n_pad)
            attention_mask.append([1] * len(x['input_ids']) + [0] * n_pad)

        return {
            'input_ids': torch.tensor(input_ids, dtype=torch.long),
            'labels': torch.tensor(labels, dtype=torch.long),
            'attention_mask': torch.tensor(attention_mask, dtype=torch.long),
        }


collator = ResponseOnlyCollator(tokenizer.pad_token_id)

TOKENIZED_TRAIN = TRAIN_DATASET.map(
    tokenize_supervised_example,
    remove_columns=TRAIN_DATASET.column_names,
    desc='Tokenizing MetaMathQA',
)
before = len(TOKENIZED_TRAIN)
TOKENIZED_TRAIN = TOKENIZED_TRAIN.filter(
    lambda x: x['supervised_tokens'] > 0,
    desc='Removing rows with no supervised tokens after truncation',
)
print('MetaMathQA train rows:', before, 'usable:', len(TOKENIZED_TRAIN))

Tokenizing MetaMathQA:   0%|          | 0/25000 [00:00<?, ? examples/s]

Tokenizing MetaMathQA:   0%|          | 114/25000 [00:00<00:22, 1114.26 examples/s]

Tokenizing MetaMathQA:   1%|          | 229/25000 [00:00<00:21, 1131.43 examples/s]

Tokenizing MetaMathQA:   1%|▏         | 347/25000 [00:00<00:21, 1145.38 examples/s]

Tokenizing MetaMathQA:   2%|▏         | 470/25000 [00:00<00:20, 1176.07 examples/s]

Tokenizing MetaMathQA:   3%|▎         | 639/25000 [00:00<00:21, 1149.57 examples/s]

Tokenizing MetaMathQA:   3%|▎         | 755/25000 [00:00<00:21, 1148.76 examples/s]

Tokenizing MetaMathQA:   4%|▎         | 921/25000 [00:00<00:21, 1118.98 examples/s]

Tokenizing MetaMathQA:   4%|▍         | 1054/25000 [00:01<00:27, 869.90 examples/s]

Tokenizing MetaMathQA:   5%|▍         | 1171/25000 [00:01<00:25, 935.07 examples/s]

Tokenizing MetaMathQA:   5%|▌         | 1282/25000 [00:01<00:24, 973.71 examples/s]

Tokenizing MetaMathQA:   6%|▌         | 1396/25000 [00:01<00:23, 1012.99 examples/s]

Tokenizing MetaMathQA:   6%|▌         | 1514/25000 [00:01<00:22, 1055.21 examples/s]

Tokenizing MetaMathQA:   7%|▋         | 1677/25000 [00:01<00:21, 1064.14 examples/s]

Tokenizing MetaMathQA:   7%|▋         | 1789/25000 [00:01<00:21, 1078.01 examples/s]

Tokenizing MetaMathQA:   8%|▊         | 1901/25000 [00:01<00:21, 1084.85 examples/s]

Tokenizing MetaMathQA:   8%|▊         | 2049/25000 [00:02<00:28, 806.11 examples/s]

Tokenizing MetaMathQA:   9%|▊         | 2165/25000 [00:02<00:26, 875.92 examples/s]

Tokenizing MetaMathQA:   9%|▉         | 2269/25000 [00:02<00:24, 912.52 examples/s]

Tokenizing MetaMathQA:  10%|▉         | 2383/25000 [00:02<00:23, 967.61 examples/s]

Tokenizing MetaMathQA:  10%|▉         | 2493/25000 [00:02<00:22, 999.93 examples/s]

Tokenizing MetaMathQA:  10%|█         | 2604/25000 [00:02<00:21, 1026.11 examples/s]

Tokenizing MetaMathQA:  11%|█         | 2714/25000 [00:02<00:21, 1044.85 examples/s]

Tokenizing MetaMathQA:  11%|█▏        | 2828/25000 [00:02<00:20, 1068.65 examples/s]

Tokenizing MetaMathQA:  12%|█▏        | 2948/25000 [00:02<00:19, 1105.22 examples/s]

Tokenizing MetaMathQA:  12%|█▏        | 3063/25000 [00:03<00:21, 1008.64 examples/s]

Tokenizing MetaMathQA:  13%|█▎        | 3173/25000 [00:03<00:21, 1031.73 examples/s]

Tokenizing MetaMathQA:  13%|█▎        | 3280/25000 [00:03<00:20, 1040.42 examples/s]

Tokenizing MetaMathQA:  14%|█▎        | 3401/25000 [00:03<00:19, 1086.16 examples/s]

Tokenizing MetaMathQA:  14%|█▍        | 3583/25000 [00:03<00:16, 1296.81 examples/s]

Tokenizing MetaMathQA:  15%|█▍        | 3732/25000 [00:03<00:15, 1348.59 examples/s]

Tokenizing MetaMathQA:  16%|█▌        | 3898/25000 [00:03<00:14, 1438.56 examples/s]

Tokenizing MetaMathQA:  16%|█▋        | 4080/25000 [00:03<00:15, 1348.95 examples/s]

Tokenizing MetaMathQA:  17%|█▋        | 4234/25000 [00:03<00:14, 1398.53 examples/s]

Tokenizing MetaMathQA:  18%|█▊        | 4409/25000 [00:03<00:13, 1494.16 examples/s]

Tokenizing MetaMathQA:  18%|█▊        | 4589/25000 [00:04<00:12, 1578.51 examples/s]

Tokenizing MetaMathQA:  19%|█▉        | 4755/25000 [00:04<00:12, 1599.78 examples/s]

Tokenizing MetaMathQA:  20%|█▉        | 4927/25000 [00:04<00:12, 1631.17 examples/s]

Tokenizing MetaMathQA:  21%|██        | 5167/25000 [00:04<00:12, 1526.55 examples/s]

Tokenizing MetaMathQA:  21%|██▏       | 5333/25000 [00:04<00:12, 1557.58 examples/s]

Tokenizing MetaMathQA:  22%|██▏       | 5573/25000 [00:04<00:12, 1567.04 examples/s]

Tokenizing MetaMathQA:  23%|██▎       | 5738/25000 [00:04<00:12, 1585.76 examples/s]

Tokenizing MetaMathQA:  24%|██▎       | 5915/25000 [00:05<00:17, 1103.68 examples/s]

Tokenizing MetaMathQA:  24%|██▍       | 6110/25000 [00:05<00:16, 1156.60 examples/s]

Tokenizing MetaMathQA:  25%|██▌       | 6274/25000 [00:05<00:14, 1255.65 examples/s]

Tokenizing MetaMathQA:  26%|██▌       | 6444/25000 [00:05<00:13, 1354.26 examples/s]

Tokenizing MetaMathQA:  26%|██▋       | 6603/25000 [00:05<00:13, 1408.46 examples/s]

Tokenizing MetaMathQA:  27%|██▋       | 6771/25000 [00:05<00:12, 1477.15 examples/s]

Tokenizing MetaMathQA:  28%|██▊       | 6944/25000 [00:05<00:11, 1543.24 examples/s]

Tokenizing MetaMathQA:  29%|██▊       | 7169/25000 [00:05<00:11, 1493.71 examples/s]

Tokenizing MetaMathQA:  29%|██▉       | 7336/25000 [00:05<00:11, 1535.57 examples/s]

Tokenizing MetaMathQA:  30%|███       | 7515/25000 [00:06<00:10, 1600.94 examples/s]

Tokenizing MetaMathQA:  31%|███       | 7688/25000 [00:06<00:10, 1635.30 examples/s]

Tokenizing MetaMathQA:  31%|███▏      | 7860/25000 [00:06<00:10, 1657.95 examples/s]

Tokenizing MetaMathQA:  32%|███▏      | 8077/25000 [00:06<00:11, 1534.24 examples/s]

Tokenizing MetaMathQA:  33%|███▎      | 8289/25000 [00:06<00:12, 1331.94 examples/s]

Tokenizing MetaMathQA:  34%|███▍      | 8453/25000 [00:06<00:11, 1397.42 examples/s]

Tokenizing MetaMathQA:  34%|███▍      | 8617/25000 [00:06<00:11, 1455.08 examples/s]

Tokenizing MetaMathQA:  35%|███▌      | 8773/25000 [00:06<00:10, 1479.46 examples/s]

Tokenizing MetaMathQA:  36%|███▌      | 8927/25000 [00:07<00:10, 1493.83 examples/s]

Tokenizing MetaMathQA:  36%|███▋      | 9083/25000 [00:07<00:11, 1413.53 examples/s]

Tokenizing MetaMathQA:  37%|███▋      | 9244/25000 [00:07<00:10, 1463.69 examples/s]

Tokenizing MetaMathQA:  38%|███▊      | 9409/25000 [00:07<00:10, 1514.13 examples/s]

Tokenizing MetaMathQA:  38%|███▊      | 9568/25000 [00:07<00:10, 1530.33 examples/s]

Tokenizing MetaMathQA:  39%|███▉      | 9740/25000 [00:07<00:09, 1583.14 examples/s]

Tokenizing MetaMathQA:  40%|███▉      | 9909/25000 [00:07<00:09, 1612.08 examples/s]

Tokenizing MetaMathQA:  40%|████      | 10094/25000 [00:07<00:10, 1464.60 examples/s]

Tokenizing MetaMathQA:  41%|████      | 10245/25000 [00:07<00:10, 1473.31 examples/s]

Tokenizing MetaMathQA:  42%|████▏     | 10406/25000 [00:08<00:09, 1507.91 examples/s]

Tokenizing MetaMathQA:  42%|████▏     | 10568/25000 [00:08<00:09, 1536.36 examples/s]

Tokenizing MetaMathQA:  43%|████▎     | 10806/25000 [00:08<00:09, 1550.66 examples/s]

Tokenizing MetaMathQA:  44%|████▍     | 10966/25000 [00:08<00:08, 1561.10 examples/s]

Tokenizing MetaMathQA:  45%|████▍     | 11152/25000 [00:08<00:09, 1424.19 examples/s]

Tokenizing MetaMathQA:  45%|████▌     | 11306/25000 [00:08<00:09, 1452.55 examples/s]

Tokenizing MetaMathQA:  46%|████▌     | 11466/25000 [00:08<00:09, 1489.59 examples/s]

Tokenizing MetaMathQA:  47%|████▋     | 11644/25000 [00:08<00:08, 1566.87 examples/s]

Tokenizing MetaMathQA:  47%|████▋     | 11815/25000 [00:08<00:08, 1604.51 examples/s]

Tokenizing MetaMathQA:  48%|████▊     | 12020/25000 [00:09<00:08, 1511.17 examples/s]

Tokenizing MetaMathQA:  49%|████▉     | 12192/25000 [00:09<00:08, 1562.49 examples/s]

Tokenizing MetaMathQA:  49%|████▉     | 12354/25000 [00:09<00:08, 1575.65 examples/s]

Tokenizing MetaMathQA:  50%|█████     | 12518/25000 [00:09<00:07, 1590.60 examples/s]

Tokenizing MetaMathQA:  51%|█████     | 12683/25000 [00:09<00:07, 1602.48 examples/s]

Tokenizing MetaMathQA:  51%|█████▏    | 12855/25000 [00:09<00:07, 1634.52 examples/s]

Tokenizing MetaMathQA:  52%|█████▏    | 13090/25000 [00:09<00:07, 1562.74 examples/s]

Tokenizing MetaMathQA:  53%|█████▎    | 13262/25000 [00:09<00:07, 1600.78 examples/s]

Tokenizing MetaMathQA:  54%|█████▎    | 13428/25000 [00:09<00:07, 1613.49 examples/s]

Tokenizing MetaMathQA:  54%|█████▍    | 13604/25000 [00:10<00:06, 1652.25 examples/s]

Tokenizing MetaMathQA:  55%|█████▌    | 13774/25000 [00:10<00:06, 1662.45 examples/s]

Tokenizing MetaMathQA:  56%|█████▌    | 13947/25000 [00:10<00:06, 1680.17 examples/s]

Tokenizing MetaMathQA:  57%|█████▋    | 14150/25000 [00:10<00:07, 1481.39 examples/s]

Tokenizing MetaMathQA:  57%|█████▋    | 14306/25000 [00:10<00:07, 1500.53 examples/s]

Tokenizing MetaMathQA:  58%|█████▊    | 14463/25000 [00:10<00:06, 1516.66 examples/s]

Tokenizing MetaMathQA:  59%|█████▊    | 14627/25000 [00:10<00:06, 1540.20 examples/s]

Tokenizing MetaMathQA:  59%|█████▉    | 14794/25000 [00:10<00:06, 1574.55 examples/s]

Tokenizing MetaMathQA:  60%|█████▉    | 14959/25000 [00:10<00:06, 1589.85 examples/s]

Tokenizing MetaMathQA:  61%|██████    | 15166/25000 [00:11<00:06, 1497.42 examples/s]

Tokenizing MetaMathQA:  62%|██████▏   | 15399/25000 [00:11<00:06, 1511.48 examples/s]

Tokenizing MetaMathQA:  62%|██████▏   | 15560/25000 [00:11<00:06, 1533.80 examples/s]

Tokenizing MetaMathQA:  63%|██████▎   | 15733/25000 [00:11<00:05, 1579.55 examples/s]

Tokenizing MetaMathQA:  64%|██████▎   | 15910/25000 [00:11<00:05, 1629.27 examples/s]

Tokenizing MetaMathQA:  64%|██████▍   | 16080/25000 [00:11<00:06, 1344.41 examples/s]

Tokenizing MetaMathQA:  65%|██████▍   | 16243/25000 [00:11<00:06, 1409.47 examples/s]

Tokenizing MetaMathQA:  66%|██████▌   | 16409/25000 [00:11<00:05, 1472.67 examples/s]

Tokenizing MetaMathQA:  66%|██████▋   | 16568/25000 [00:12<00:05, 1503.34 examples/s]

Tokenizing MetaMathQA:  67%|██████▋   | 16735/25000 [00:12<00:05, 1545.98 examples/s]

Tokenizing MetaMathQA:  68%|██████▊   | 16896/25000 [00:12<00:05, 1561.11 examples/s]

Tokenizing MetaMathQA:  68%|██████▊   | 17104/25000 [00:12<00:05, 1491.65 examples/s]

Tokenizing MetaMathQA:  69%|██████▉   | 17266/25000 [00:12<00:05, 1523.00 examples/s]

Tokenizing MetaMathQA:  70%|███████   | 17502/25000 [00:12<00:04, 1536.43 examples/s]

Tokenizing MetaMathQA:  71%|███████   | 17671/25000 [00:12<00:04, 1573.08 examples/s]

Tokenizing MetaMathQA:  71%|███████▏  | 17850/25000 [00:12<00:04, 1630.70 examples/s]

Tokenizing MetaMathQA:  72%|███████▏  | 18084/25000 [00:13<00:04, 1519.04 examples/s]

Tokenizing MetaMathQA:  73%|███████▎  | 18254/25000 [00:13<00:04, 1561.61 examples/s]

Tokenizing MetaMathQA:  74%|███████▎  | 18414/25000 [00:13<00:04, 1569.43 examples/s]

Tokenizing MetaMathQA:  74%|███████▍  | 18575/25000 [00:13<00:04, 1576.12 examples/s]

Tokenizing MetaMathQA:  75%|███████▌  | 18751/25000 [00:13<00:03, 1623.57 examples/s]

Tokenizing MetaMathQA:  76%|███████▌  | 18919/25000 [00:13<00:03, 1635.58 examples/s]

Tokenizing MetaMathQA:  76%|███████▋  | 19101/25000 [00:13<00:03, 1586.22 examples/s]

Tokenizing MetaMathQA:  77%|███████▋  | 19270/25000 [00:13<00:03, 1612.17 examples/s]

Tokenizing MetaMathQA:  78%|███████▊  | 19442/25000 [00:13<00:03, 1641.02 examples/s]

Tokenizing MetaMathQA:  79%|███████▉  | 19688/25000 [00:13<00:03, 1636.40 examples/s]

Tokenizing MetaMathQA:  79%|███████▉  | 19865/25000 [00:14<00:03, 1667.21 examples/s]

Tokenizing MetaMathQA:  80%|████████  | 20085/25000 [00:14<00:03, 1542.98 examples/s]

Tokenizing MetaMathQA:  81%|████████  | 20258/25000 [00:14<00:02, 1586.10 examples/s]

Tokenizing MetaMathQA:  82%|████████▏ | 20425/25000 [00:14<00:02, 1604.59 examples/s]

Tokenizing MetaMathQA:  82%|████████▏ | 20596/25000 [00:14<00:02, 1629.87 examples/s]

Tokenizing MetaMathQA:  83%|████████▎ | 20771/25000 [00:14<00:02, 1661.44 examples/s]

Tokenizing MetaMathQA:  84%|████████▍ | 21000/25000 [00:14<00:02, 1545.60 examples/s]

Tokenizing MetaMathQA:  85%|████████▍ | 21168/25000 [00:14<00:02, 1577.90 examples/s]

Tokenizing MetaMathQA:  85%|████████▌ | 21339/25000 [00:15<00:02, 1611.23 examples/s]

Tokenizing MetaMathQA:  86%|████████▌ | 21513/25000 [00:15<00:02, 1644.61 examples/s]

Tokenizing MetaMathQA:  87%|████████▋ | 21688/25000 [00:15<00:01, 1671.73 examples/s]

Tokenizing MetaMathQA:  87%|████████▋ | 21867/25000 [00:15<00:01, 1703.31 examples/s]

Tokenizing MetaMathQA:  88%|████████▊ | 22085/25000 [00:15<00:01, 1552.92 examples/s]

Tokenizing MetaMathQA:  89%|████████▉ | 22250/25000 [00:15<00:01, 1574.54 examples/s]

Tokenizing MetaMathQA:  90%|████████▉ | 22487/25000 [00:15<00:01, 1572.95 examples/s]

Tokenizing MetaMathQA:  91%|█████████ | 22658/25000 [00:15<00:01, 1605.34 examples/s]

Tokenizing MetaMathQA:  91%|█████████▏| 22831/25000 [00:15<00:01, 1634.59 examples/s]

Tokenizing MetaMathQA:  92%|█████████▏| 23000/25000 [00:16<00:01, 1524.22 examples/s]

Tokenizing MetaMathQA:  93%|█████████▎| 23167/25000 [00:16<00:01, 1561.07 examples/s]

Tokenizing MetaMathQA:  93%|█████████▎| 23343/25000 [00:16<00:01, 1612.09 examples/s]

Tokenizing MetaMathQA:  94%|█████████▍| 23508/25000 [00:16<00:00, 1621.20 examples/s]

Tokenizing MetaMathQA:  95%|█████████▍| 23680/25000 [00:16<00:00, 1440.08 examples/s]

Tokenizing MetaMathQA:  95%|█████████▌| 23852/25000 [00:16<00:00, 1513.45 examples/s]

Tokenizing MetaMathQA:  96%|█████████▋| 24084/25000 [00:16<00:00, 1454.19 examples/s]

Tokenizing MetaMathQA:  97%|█████████▋| 24253/25000 [00:16<00:00, 1510.20 examples/s]

Tokenizing MetaMathQA:  98%|█████████▊| 24431/25000 [00:17<00:00, 1578.85 examples/s]

Tokenizing MetaMathQA:  98%|█████████▊| 24594/25000 [00:17<00:00, 1591.10 examples/s]

Tokenizing MetaMathQA:  99%|█████████▉| 24766/25000 [00:17<00:00, 1620.07 examples/s]

Tokenizing MetaMathQA: 100%|██████████| 25000/25000 [00:17<00:00, 1538.49 examples/s]

Tokenizing MetaMathQA: 100%|██████████| 25000/25000 [00:17<00:00, 1436.74 examples/s]

Removing rows with no supervised tokens after truncation:   0%|          | 0/25000 [00:00<?, ? examples/s]

Removing rows with no supervised tokens after truncation:  24%|██▍       | 6000/25000 [00:00<00:00, 50717.61 examples/s]

Removing rows with no supervised tokens after truncation:  48%|████▊     | 12000/25000 [00:00<00:00, 50910.86 examples/s]

Removing rows with no supervised tokens after truncation:  72%|███████▏  | 18000/25000 [00:00<00:00, 51696.31 examples/s]

Removing rows with no supervised tokens after truncation:  96%|█████████▌| 24000/25000 [00:00<00:00, 51249.52 examples/s]

Removing rows with no supervised tokens after truncation: 100%|██████████| 25000/25000 [00:00<00:00, 50890.11 examples/s]

MetaMathQA train rows: 25000 usable: 24975

In [8]:
def load_fresh_model(to_device=False):
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        dtype=MODEL_DTYPE,
        device_map='cpu',
        low_cpu_mem_usage=True,
    )
    model.config.use_cache = True
    if to_device:
        model = model.to(TRAIN_DEVICE)
    return model


def cleanup_model(model=None):
    if model is not None:
        try:
            model.to('cpu')
        except Exception:
            pass
        del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

In [9]:
class PiSSALinear(nn.Module):
    def __init__(self, weight_residual, pissa_A, pissa_B, bias=None):
        super().__init__()
        out_features, in_features = weight_residual.shape
        rank = pissa_A.shape[1]
        assert pissa_A.shape == (out_features, rank)
        assert pissa_B.shape == (rank, in_features)

        self.rank = rank
        self.weight = nn.Parameter(weight_residual.contiguous(), requires_grad=False)
        self.pissa_A = nn.Parameter(pissa_A.float())
        self.pissa_B = nn.Parameter(pissa_B.float())
        if bias is None:
            self.register_parameter('bias', None)
        else:
            self.bias = nn.Parameter(bias.detach().clone(), requires_grad=False)

    def forward(self, x):
        frozen_out = F.linear(x, self.weight, self.bias)
        with torch.autocast(device_type=x.device.type, enabled=False):
            hidden = F.linear(x.float(), self.pissa_B)
            update = F.linear(hidden, self.pissa_A)
        return frozen_out + update.to(frozen_out.dtype)

In [10]:
@dataclass
class PiSSAInitStats:
    name: str
    rank: int
    component: str
    relative_error_stored: float

@torch.no_grad()
def pissa_from_linear_exact(linear, rank, component, layer_name=''):
    W = linear.weight.detach().to(SVD_DEVICE, dtype=torch.float32)
    out_features, in_features = W.shape
    k = min(out_features, in_features)
    if rank > k:
        raise ValueError(f'{layer_name}: rank={rank} > max rank={k}')

    U, S, Vh = torch.linalg.svd(W, full_matrices=False)

    # ====================================================================================================
    # TODO for Question 3
    """
    Hint:
    # Set the starting point at the 25% position of singular values S
     start = len(S) // 4
    
    """

    if component == 'default':
        start = 0                     # top `rank` singular values (PiSSA)
    elif component == 'q25':
        start = len(S) // 4           # `rank` consecutive values from the 25% position
    elif component == 'q50':
        start = len(S) // 2           # `rank` consecutive values from the 50% position
    elif component == 'bottom':
        start = len(S) - rank         # the smallest `rank` singular values
    else:
        raise ValueError(component)
    end = start + rank
    assert 0 <= start and end <= len(S), (layer_name, component, start, end, len(S))

    # ====================================================================================================
        
    U_r, S_r, Vh_r = U[:, start:end], S[start:end], Vh[start:end, :]
    sqrt_S = torch.sqrt(S_r)
    A = U_r * sqrt_S.unsqueeze(0)
    B = sqrt_S.unsqueeze(1) * Vh_r
    W_res = W - (A @ B)

    stored = W_res.to(linear.weight.dtype).cpu()
    A_cpu, B_cpu, W_cpu = A.cpu(), B.cpu(), W.cpu()
    rel_err = (
        torch.linalg.vector_norm(W_cpu - (stored.float() + A_cpu @ B_cpu))
        / torch.linalg.vector_norm(W_cpu)
    ).item()

    replacement = PiSSALinear(
        stored,
        A_cpu,
        B_cpu,
        None if linear.bias is None else linear.bias.detach().cpu(),
    )
    stats = PiSSAInitStats(layer_name, rank, component, rel_err)

    del W, U, S, Vh, U_r, S_r, Vh_r, sqrt_S, A, B, W_res
    torch.cuda.empty_cache()
    gc.collect()
    return replacement, stats

In [11]:
TARGET_MODULE_NAMES = {
    'q_proj', 'k_proj', 'v_proj', 'o_proj',
    'gate_proj', 'up_proj', 'down_proj',
}


def freeze_model(model):
    for p in model.parameters():
        p.requires_grad = False


def get_parent_module(root, full_name):
    if '.' not in full_name:
        return root, full_name
    parent_name, child_name = full_name.rsplit('.', 1)
    return root.get_submodule(parent_name), child_name


def collect_target_linears(model):
    return [
        (name, module)
        for name, module in model.named_modules()
        if isinstance(module, nn.Linear)
        and name.rsplit('.', 1)[-1] in TARGET_MODULE_NAMES
    ]


def inject_pissa(model, rank, component):
    freeze_model(model)
    targets = collect_target_linears(model)
    stats = []

    for idx, (name, linear) in enumerate(targets, 1):
        replacement, st = pissa_from_linear_exact(
            linear, rank=rank, component=component, layer_name=name
        )

        parent, child = get_parent_module(model, name)
        setattr(parent, child, replacement)
        stats.append(st)
        if idx <= 3 or idx == len(targets):
            print(f'[{idx:3d}/{len(targets):3d}] {name}')

    return stats


def verify_trainables(model):
    suffixes = ('pissa_A', 'pissa_B')
    trainable, total, unexpected = 0, 0, []
    for name, p in model.named_parameters():
        total += p.numel()
        if p.requires_grad:
            trainable += p.numel()
            if not name.endswith(suffixes):
                unexpected.append(name)
    assert trainable > 0
    assert not unexpected, 'Unexpected trainables: ' + ', '.join(unexpected)
    print('Trainable parameters:', f'{trainable:,}', f'({100*trainable/total:.3f}%)')
    return trainable, total

@torch.no_grad()
def merge_pissa_and_unload(model):
    """Merge every PiSSALinear into a standard nn.Linear in-place.

    For this notebook's custom PiSSA parameterization, each adapted layer is
        W = W_residual + A @ B
    so merging reproduces PEFT's PiSSA merge-and-unload behavior: the custom
    adapter wrapper disappears and the model becomes a normal Transformers
    causal-LM that can be evaluated and saved standalone.
    """
    targets = [
        (name, module)
        for name, module in model.named_modules()
        if isinstance(module, PiSSALinear)
    ]
    if not targets:
        raise RuntimeError('No PiSSALinear modules found to merge.')

    merged_names = []
    for name, layer in targets:
        merged_weight = (
            layer.weight.float()
            + layer.pissa_A.float() @ layer.pissa_B.float()
        ).to(dtype=layer.weight.dtype)

        replacement = nn.Linear(
            in_features=layer.weight.shape[1],
            out_features=layer.weight.shape[0],
            bias=layer.bias is not None,
            device=layer.weight.device,
            dtype=layer.weight.dtype,
        )
        replacement.weight.copy_(merged_weight)
        replacement.weight.requires_grad_(False)

        if layer.bias is not None:
            replacement.bias.copy_(layer.bias.to(
                device=layer.weight.device,
                dtype=layer.weight.dtype,
            ))
            replacement.bias.requires_grad_(False)

        parent, child = get_parent_module(model, name)
        setattr(parent, child, replacement)
        merged_names.append(name)

    remaining = [
        name for name, module in model.named_modules()
        if isinstance(module, PiSSALinear)
    ]
    if remaining:
        raise RuntimeError(
            'PiSSA merge incomplete; remaining modules: ' + ', '.join(remaining)
        )

    print(f'Merged {len(merged_names)} PiSSA layers into standard nn.Linear layers.')
    return merged_names

In [12]:
class LossOnlyWrapper(nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.base_model = base_model

    def forward(self, **batch):
        return self.base_model(**batch).loss


def build_optimizer_and_scheduler(model, num_batches):
    trainable = [p for p in model.parameters() if p.requires_grad]
    updates_per_epoch = math.ceil(num_batches / GRAD_ACCUM_STEPS)
    total_updates = EPOCHS * updates_per_epoch
    warmup_updates = max(1, math.ceil(total_updates * WARMUP_RATIO))

    optimizer = torch.optim.AdamW(
        trainable,
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )

    def lr_lambda(step):
        if step < warmup_updates:
            return float(step + 1) / float(max(1, warmup_updates))
        progress = (step - warmup_updates) / max(1, total_updates - warmup_updates)
        return 0.5 * (1.0 + math.cos(math.pi * min(1.0, progress)))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
    return optimizer, scheduler, total_updates, warmup_updates


def train_one_task(model, train_dataset, task_name):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

    generator = torch.Generator().manual_seed(SEED)
    loader = DataLoader(
        train_dataset,
        batch_size=MICRO_BATCH_SIZE,
        shuffle=True,
        generator=generator,
        collate_fn=collator,
        num_workers=0,
        pin_memory=True,
        drop_last=False,
    )

    optimizer, scheduler, total_updates, warmup_updates = build_optimizer_and_scheduler(
        model, len(loader)
    )

    print(
        f'Training {task_name}: {len(train_dataset)} examples, '
        f'{len(loader)} micro-batches, {total_updates} updates, '
        f'{warmup_updates} warmup updates.'
    )

    model.config.use_cache = False
    model.train()
    loss_model = LossOnlyWrapper(model)
    train_model = (
        nn.DataParallel(loss_model, device_ids=[0, 1], output_device=0)
        if USE_DATA_PARALLEL
        else loss_model
    )

    scaler = torch.amp.GradScaler('cuda', enabled=True)
    optimizer.zero_grad(set_to_none=True)
    history = []
    update_step = 0
    running_loss = 0.0

    torch.cuda.synchronize()

    # TODO for Question 2
    """
    Hint: Following we have tagged the start and the end positions of training.
    """


    """This is the start of training.""" 
    train_t0 = time.perf_counter()


    for epoch in range(EPOCHS):
        progress = tqdm(loader, desc=f'Train {task_name} epoch {epoch+1}/{EPOCHS}')
        for micro_step, batch in enumerate(progress, 1):
            batch = {k: v.to(TRAIN_DEVICE, non_blocking=True) for k, v in batch.items()}

            with torch.autocast(device_type='cuda', dtype=torch.float16):
                loss = train_model(**batch)
                if loss.ndim > 0:
                    loss = loss.mean()
                scaled_loss = loss / GRAD_ACCUM_STEPS

            scaler.scale(scaled_loss).backward()
            running_loss += float(loss.detach().cpu())

            should_step = (
                micro_step % GRAD_ACCUM_STEPS == 0
                or micro_step == len(loader)
            )
            if should_step:
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
                scheduler.step()
                update_step += 1

                mean_loss = running_loss / (
                    GRAD_ACCUM_STEPS
                    if micro_step % GRAD_ACCUM_STEPS == 0
                    else (micro_step - (update_step - 1) * GRAD_ACCUM_STEPS)
                )
                history.append({
                    'update': update_step,
                    'loss': mean_loss,
                    'lr': scheduler.get_last_lr()[0],
                })
                running_loss = 0.0
                progress.set_postfix(loss=f'{mean_loss:.4f}', update=update_step)

    torch.cuda.synchronize()

    """This is the end of training."""
    train_seconds = time.perf_counter() - train_t0
    print(f'Training time for {task_name}: {train_seconds / 60:.2f} min')

    model.config.use_cache = True
    return history, train_seconds

In [13]:
def remove_right_units(string):
    # Behavioral reproduction of PiSSA utils/test_acc.py.
    if "\\text{ " in string:
        splits = string.split("\\text{ ")
        assert len(splits) == 2
        return splits[0]
    return string


def fix_sqrt(string):
    if "\\sqrt" not in string:
        return string
    splits = string.split("\\sqrt")
    new_string = splits[0]
    for split in splits[1:]:
        if split[0] != "{":
            a = split[0]
            new_substr = "\\sqrt{" + a + "}" + split[1:]
        else:
            new_substr = "\\sqrt" + split
        new_string += new_substr
    return new_string


def fix_fracs(string):
    substrs = string.split("\\frac")
    new_str = substrs[0]
    if len(substrs) > 1:
        substrs = substrs[1:]
        for substr in substrs:
            new_str += "\\frac"
            if substr[0] == "{":
                new_str += substr
            else:
                try:
                    assert len(substr) >= 2
                except AssertionError:
                    return string
                a = substr[0]
                b = substr[1]
                if b != "{":
                    if len(substr) > 2:
                        post_substr = substr[2:]
                        new_str += "{" + a + "}{" + b + "}" + post_substr
                    else:
                        new_str += "{" + a + "}{" + b + "}"
                else:
                    if len(substr) > 2:
                        post_substr = substr[2:]
                        new_str += "{" + a + "}" + b + post_substr
                    else:
                        new_str += "{" + a + "}" + b
    return new_str


def fix_a_slash_b(string):
    if len(string.split("/")) != 2:
        return string
    a = string.split("/")[0]
    b = string.split("/")[1]
    try:
        a_int = int(a)
        b_int = int(b)
        assert string == "{}/{}".format(a_int, b_int)
        return "\\frac{" + str(a_int) + "}{" + str(b_int) + "}"
    except (AssertionError, ValueError):
        return string


def strip_pissa_math_string(string):
    string = str(string)
    string = string.replace("\n", "")
    string = string.replace("\\!", "")
    string = string.replace("\\\\", "\\")
    string = string.replace("tfrac", "frac")
    string = string.replace("dfrac", "frac")
    string = string.replace("\\left", "")
    string = string.replace("\\right", "")
    string = string.replace("^{\\circ}", "")
    string = string.replace("^\\circ", "")
    string = string.replace("\\$", "")
    string = remove_right_units(string)
    string = string.replace("\\%", "")
    string = string.replace("\\%", "")
    string = string.replace(" .", " 0.")
    string = string.replace("{.", "{0.")

    if len(string) == 0:
        return string
    if string[0] == ".":
        string = "0" + string

    if len(string.split("=")) == 2:
        if len(string.split("=")[0]) <= 2:
            string = string.split("=")[1]

    string = fix_sqrt(string)
    string = string.replace(" ", "")
    string = fix_fracs(string)

    if string == "0.5":
        string = "\\frac{1}{2}"

    string = fix_a_slash_b(string)
    return string


def pissa_math_is_equiv(str1, str2):
    if str1 is None and str2 is None:
        return True
    if str1 is None or str2 is None:
        return False
    try:
        return strip_pissa_math_string(str1) == strip_pissa_math_string(str2)
    except Exception:
        return str1 == str2


def process_pissa_math_result(completion, answer):
    split_ans = str(completion).split("The answer is: ")
    if len(split_ans) <= 1:
        return False

    ans = split_ans[-1]
    extract_ans_temp = ans.split(".\n")[0].strip()
    if len(extract_ans_temp) > 0 and extract_ans_temp[-1] == ".":
        extract_ans = extract_ans_temp[:-1]
    else:
        extract_ans = extract_ans_temp
    extract_ans = extract_ans.strip()
    return pissa_math_is_equiv(extract_ans, str(answer))


def is_number(s):
    try:
        float(s)
        return True
    except Exception:
        return False


def extract_pissa_gsm8k_number(completion):
    # Behavioral reproduction of utils/test_acc.py for GSM8K.
    parts = str(completion).split("The answer is: ")
    if len(parts) <= 1:
        return None
    tail = parts[-1].strip()
    match = re.search(r"[\-+]?\d*[\.,/]?\d+", tail)
    if not match:
        return None
    token = match.group().replace(",", "")

    if "/" in token:
        numerator, denominator = token.split("/", 1)
        if not (is_number(numerator) and is_number(denominator)):
            return None
        if float(denominator) == 0:
            return round(float(numerator))
        return round(float(Fraction(token)))

    value = float(token)
    if math.isinf(value):
        return None
    return round(value)


def normalize_gsm8k_gold(value):
    text = str(value).strip().replace(",", "")
    if "####" in text:
        text = text.split("####")[-1].strip()
    match = re.search(r"[\-+]?\d+(?:\.\d+)?", text)
    if not match:
        raise ValueError(f"Cannot parse GSM8K gold: {value!r}")
    return float(match.group())

def extract_last_boxed(text):
    """
    Extract the content of the last \\boxed{...}, including
    nested braces such as \\boxed{\\frac{1}{2}}.
    """
    text = str(text)
    marker = "\\boxed{"

    start = text.rfind(marker)
    if start == -1:
        return None

    i = start + len(marker)
    depth = 1
    j = i

    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1

            if depth == 0:
                return text[i:j].strip()

        j += 1

    return None


def clean_robust_answer_text(text):
    text = str(text).strip()

    # Remove common math wrappers.
    text = text.strip("$")
    text = text.replace("\\(", "")
    text = text.replace("\\)", "")
    text = text.replace("\\[", "")
    text = text.replace("\\]", "")

    text = text.strip()

    # Harmless final punctuation.
    while text.endswith((".", ",", ";")):
        text = text[:-1].strip()

    return text


def extract_robust_answer_text(completion):
    """
    Forgiving final-answer extraction.

    Accepts examples such as:
        The answer is: 42
        The answer is 42
        The answer: 42
        Answer: 42
        Answer 42
        Final answer = 42
        Therefore, the answer is 42
        #### 42
        \\boxed{42}

    Returns:
        (answer_text, extraction_source)
    """
    text = str(completion)

    # 1. Look for answer/final-answer markers. Colon is optional.
    marker_pattern = re.compile(
        r"(?:the\s+)?(?:final\s+)?answer"
        r"\s*(?:is\s*)?"
        r"(?::|=)?"
        r"\s*([^\n]+)",
        flags=re.IGNORECASE,
    )

    matches = list(marker_pattern.finditer(text))

    if matches:
        candidate = matches[-1].group(1).strip()

        # e.g. "The answer is: \\boxed{42}"
        boxed = extract_last_boxed(candidate)

        if boxed is not None:
            return (
                clean_robust_answer_text(boxed),
                "answer_marker_boxed",
            )

        return (
            clean_robust_answer_text(candidate),
            "answer_marker",
        )

    # 2. GSM8K-style #### answer.
    if "####" in text:
        candidate = text.rsplit("####", 1)[-1].strip()

        if candidate:
            candidate = candidate.splitlines()[0].strip()

            if candidate:
                return (
                    clean_robust_answer_text(candidate),
                    "hash_marker",
                )

    # 3. MATH-style \\boxed{...}.
    boxed = extract_last_boxed(text)

    if boxed is not None:
        return (
            clean_robust_answer_text(boxed),
            "boxed",
        )

    # No reliable final-answer pattern found.
    # Treat as unparsed rather than guessing from the last line.
    return None, None


def parse_numeric_token(token):
    """
    Convert a plain number or fraction to float.
    """
    if token is None:
        return None

    token = str(token).strip().replace(",", "")

    try:
        if "/" in token:
            return float(Fraction(token))

        return float(token)

    except Exception:
        return None


def extract_robust_gsm8k_number(completion):
    """
    Forgiving GSM8K extraction.

    First attempts to identify an answer region, then extracts
    the LAST number/fraction from that region.
    """
    candidate, source = extract_robust_answer_text(completion)

    if candidate is None:
        candidate = str(completion)
        source = "full_text_fallback"

    # Supports: 42, -42, 1,234, 42.5, 1/2.
    number_pattern = re.compile(
        r"[-+]?"
        r"(?:\d{1,3}(?:,\d{3})+|\d+|\.\d+)"
        r"(?:\.\d+)?"
        r"(?:/\d+(?:\.\d+)?)?"
    )

    matches = number_pattern.findall(candidate)

    if not matches:
        # As a final fallback, inspect the entire completion.
        matches = number_pattern.findall(str(completion))
        source = "last_number_fallback"

    if not matches:
        return None, source

    # Usually safest for generated solutions: final value = final number.
    value = parse_numeric_token(matches[-1])

    return value, source


def simple_math_numeric_value(text):
    """
    Handle simple numerical equivalence for MATH:
        0.5 == 1/2 == \\frac{1}{2}

    This intentionally does NOT try to solve arbitrary symbolic expressions.
    """
    if text is None:
        return None

    text = clean_robust_answer_text(text)
    text = text.replace(",", "")

    # LaTeX fraction: \\frac{1}{2}
    frac_match = re.fullmatch(
        r"\\frac\{([+-]?(?:\d+(?:\.\d+)?|\.\d+))\}"
        r"\{([+-]?(?:\d+(?:\.\d+)?|\.\d+))\}",
        text,
    )

    if frac_match:
        numerator = float(frac_match.group(1))
        denominator = float(frac_match.group(2))

        if denominator == 0:
            return None

        return numerator / denominator

    # Plain fraction: 1/2
    slash_match = re.fullmatch(
        r"([+-]?(?:\d+(?:\.\d+)?|\.\d+))"
        r"/"
        r"([+-]?(?:\d+(?:\.\d+)?|\.\d+))",
        text,
    )

    if slash_match:
        numerator = float(slash_match.group(1))
        denominator = float(slash_match.group(2))

        if denominator == 0:
            return None

        return numerator / denominator

    # Plain number.
    try:
        return float(text)
    except Exception:
        return None


def robust_math_is_equiv(pred, gold):
    """
    Conservative robust MATH comparison.

    1. Try PiSSA's original normalization.
    2. Try simple numerical equivalence.
    """
    if pred is None or gold is None:
        return False

    pred = clean_robust_answer_text(pred)
    gold = clean_robust_answer_text(gold)

    # First preserve PiSSA-compatible normalization.
    if pissa_math_is_equiv(pred, gold):
        return True

    # Then allow simple numerical equivalence.
    pred_num = simple_math_numeric_value(pred)
    gold_num = simple_math_numeric_value(gold)

    if pred_num is not None and gold_num is not None:
        return math.isclose(
            pred_num,
            gold_num,
            rel_tol=0.0,
            abs_tol=1e-9,
        )

    return False


@torch.no_grad()
def evaluate_generation(model, dataset, task_name, max_examples=None):
    if task_name not in EVAL_TASKS:
        raise ValueError(f"Unsupported evaluation task: {task_name}")

    model.eval()
    model.config.use_cache = True

    n = len(dataset) if max_examples is None else min(len(dataset), max_examples)

    old_padding_side = tokenizer.padding_side
    old_truncation_side = tokenizer.truncation_side
    tokenizer.padding_side = "left"
    tokenizer.truncation_side = "left"

    correct = 0
    unparsed = 0
    records = []

    torch.cuda.synchronize()
    t0 = time.perf_counter()

    try:
        for start in tqdm(range(0, n, EVAL_BATCH_SIZE), desc=f"Eval {task_name}"):
            end = min(start + EVAL_BATCH_SIZE, n)
            rows = dataset[start:end]
            prompts = [str(x) for x in rows["instruction"]]

            enc = tokenizer(
                prompts,
                padding=True,
                truncation=True,
                max_length=MAX_LENGTH,
                return_tensors="pt",
            )
            enc = {k: v.to(TRAIN_DEVICE) for k, v in enc.items()}

            generated = model.generate(
                **enc,
                do_sample=False,
                max_new_tokens=EVAL_MAX_NEW_TOKENS,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
            prompt_width = enc["input_ids"].shape[1]
            decoded = tokenizer.batch_decode(
                generated[:, prompt_width:],
                skip_special_tokens=True,
            )

            for i, text in enumerate(decoded):
                gold_raw = rows["gold_answer"][i]

                if task_name == "gsm8k":
                    gold = normalize_gsm8k_gold(gold_raw)
                    pred, extraction_source = extract_robust_gsm8k_number(text)

                    ok = (
                        pred is not None
                        and math.isclose(
                            float(pred),
                            float(gold),
                            rel_tol=0.0,
                            abs_tol=1e-9,
                        )
                    )
                    parsed_answer = None if pred is None else str(pred)
                    normalized_gold = str(gold)
                    parsed = pred is not None

                else:
                    pred, extraction_source = extract_robust_answer_text(text)
                    ok = (
                        pred is not None
                        and robust_math_is_equiv(pred, gold_raw)
                    )
                    parsed_answer = None if pred is None else str(pred)
                    normalized_gold = str(gold_raw)
                    parsed = pred is not None

                if not parsed:
                    unparsed += 1

                correct += int(ok)
                records.append({
                    "task": task_name,
                    "instruction": prompts[i],
                    "prediction_text": text,
                    "pred_answer": parsed_answer,
                    "gold_answer": normalized_gold,
                    "correct": bool(ok),
                    "extraction_source": extraction_source,
                })
    finally:
        tokenizer.padding_side = old_padding_side
        tokenizer.truncation_side = old_truncation_side

    torch.cuda.synchronize()
    eval_seconds = time.perf_counter() - t0

    return {
        "task": task_name,
        "accuracy": correct / n if n else 0.0,
        "correct": correct,
        "total": n,
        "unparsed": unparsed,
        "eval_seconds": eval_seconds,
        "records": records,
        "evaluation_protocol": (
            "robust_generation_numeric_match"
            if task_name == "gsm8k"
            else "robust_generation_math_equivalence"
        ),
    }

In [14]:
def evaluate_task(
    model,
    dataset,
    task_name,
    max_examples=None,
):
    return evaluate_generation(
        model=model,
        dataset=dataset,
        task_name=task_name,
        max_examples=max_examples,
    )


def evaluate_all_tasks(model, max_examples=None):
    results = {}
    for task in EVAL_TASKS:
        results[task] = evaluate_task(
            model,
            EVAL_DATASETS[task],
            task,
            max_examples=max_examples,
        )
    return results


def flatten_eval_results(eval_results, prefix=''):
    flat = {}
    for task, result in eval_results.items():
        stem = f'{prefix}{task}_'
        for key in ['accuracy', 'correct', 'total', 'unparsed', 'eval_seconds']:
            flat[stem + key] = result[key]
    return flat


def combine_eval_records(eval_results):
    records = []
    for task in EVAL_TASKS:
        records.extend(eval_results[task]['records'])
    return records

In [15]:
def write_jsonl(path, records):
    with Path(path).open('w', encoding='utf-8') as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False, default=str) + '\n')


def safe_run_tag(method, rank=None, component=None):
    if method == 'fresh':
        return 'metamath_fresh'
    if method != 'pissa':
        raise ValueError(f'Unsupported method: {method}')
    return f'metamath_pissa_{component}_r{rank}'


def save_summary(summary, records=None):
    tag = summary['run_tag']
    path = RESULT_ROOT / f'{tag}_summary.json'
    path.write_text(json.dumps(summary, indent=2, default=str), encoding='utf-8')
    if SAVE_PREDICTIONS and records is not None:
        write_jsonl(RESULT_ROOT / f'{tag}_predictions.jsonl', records)
    return path


def save_training_time_partial(summary):
    tag = summary['run_tag']
    path = RESULT_ROOT / f'{tag}_training_time.json'
    path.write_text(json.dumps(summary, indent=2, default=str), encoding='utf-8')
    return path


def save_master_results(rows):
    df = pd.DataFrame(rows)
    df.to_csv(RESULT_ROOT / 'benchmark_results.csv', index=False)
    (RESULT_ROOT / 'benchmark_results.json').write_text(
        json.dumps(rows, indent=2, default=str), encoding='utf-8'
    )
    return df

In [16]:
def run_fresh_baseline(max_eval_examples=1000):
    tag = safe_run_tag('fresh')
    print('\n' + '='*80)
    print('FRESH BASELINE: evaluate GSM8K + MATH')
    print('='*80)

    model = load_fresh_model(to_device=True)
    
    try:
        eval_results = evaluate_all_tasks(
            model,
            max_examples=max_eval_examples,
        )
        summary = {
            'run_tag': tag,
            'training_dataset': METAMATH_TRAIN_DATASET_ID,
            'training_examples': 0,
            'method': 'fresh',
            'rank': None,
            'component': None,
            **flatten_eval_results(eval_results),
            'init_seconds': 0.0,
            'trainable_parameters': 0,
            'status': 'ok',
            'seed': SEED,
        }
        save_summary(summary, combine_eval_records(eval_results))
        return summary
    finally:
        cleanup_model(model)


def run_pissa_experiment(rank, component, max_eval_examples=1000):
    method = 'pissa'
    tag = safe_run_tag(method, rank, component)
    print('\n' + '='*80)
    print(tag)
    print('='*80)

    model = load_fresh_model(to_device=False)
    
    try:
        torch.manual_seed(SEED)
        torch.cuda.manual_seed_all(SEED)

        torch.cuda.synchronize()
        init_t0 = time.perf_counter()
        init_stats = inject_pissa(
            model,
            rank=rank,
            component=component,
        )
        torch.cuda.synchronize()
        init_seconds = time.perf_counter() - init_t0

        trainable, total_params = verify_trainables(model)
        model = model.to(TRAIN_DEVICE)

        initial_results = None

        history, train_seconds = train_one_task(
            model,
            TOKENIZED_TRAIN,
            'metamath',
        )

        history_df = pd.DataFrame(history)
        history_df['training_dataset'] = METAMATH_TRAIN_DATASET_ID
        history_df['method'] = method
        history_df['rank'] = rank
        history_df['component'] = component

        history_path = RESULT_ROOT / f'{tag}_training_history.csv'
        history_df.to_csv(history_path, index=False)
        print('Training history saved:', history_path)

        partial = {
            'run_tag': tag,
            'training_dataset': METAMATH_TRAIN_DATASET_ID,
            'training_examples': len(TOKENIZED_TRAIN),
            'method': method,
            'rank': rank,
            'component': component,
            'init_seconds': init_seconds,
            'train_seconds': train_seconds,
            'train_minutes': train_seconds / 60,
            'trainable_parameters': trainable,
            'status': 'trained_pending_merge_eval',
            'seed': SEED,
        }
        save_training_time_partial(partial)

        if SAVE_ADAPTERS:
            adapter_state = {
                name: p.detach().cpu()
                for name, p in model.named_parameters()
                if p.requires_grad
            }
            adapter_path = RESULT_ROOT / f'{tag}_adapter.pt'
            torch.save(
                {'metadata': partial, 'state_dict': adapter_state},
                adapter_path,
            )
            print('PiSSA adapter saved:', adapter_path)

        torch.cuda.synchronize()
        merge_t0 = time.perf_counter()
        merged_names = merge_pissa_and_unload(model)
        torch.cuda.synchronize()
        merge_seconds = time.perf_counter() - merge_t0

        assert not any(
            isinstance(module, PiSSALinear)
            for module in model.modules()
        ), 'Evaluation must use the merged standalone model.'
        print(f'PiSSA merge time: {merge_seconds:.2f}s')
        print('Evaluating merged model on GSM8K + MATH...')

        eval_results = evaluate_all_tasks(
            model,
            max_examples=max_eval_examples,
        )

        full_model_path = RESULT_ROOT / f'{tag}_full_model'
        if SAVE_FULL_MODEL:
            model = model.to('cpu')
            gc.collect()
            torch.cuda.empty_cache()
            model.save_pretrained(
                full_model_path,
                safe_serialization=True,
            )
            tokenizer.save_pretrained(full_model_path)
            print('Merged full model saved:', full_model_path)

        summary = {
            **partial,
            **flatten_eval_results(eval_results),
            'merge_seconds': merge_seconds,
            'merged_layer_count': len(merged_names),
            'evaluated_after_merge': True,
            'full_model_saved': bool(SAVE_FULL_MODEL),
            'full_model_path': str(full_model_path) if SAVE_FULL_MODEL else None,
            'status': 'ok',
            'final_training_loss': history[-1]['loss'] if history else None,
            'training_history_path': str(history_path),
            'total_parameters_with_adapter': total_params,
            'max_pissa_reconstruction_error': max(
                x.relative_error_stored for x in init_stats
            ),
        }

        if initial_results is not None:
            summary.update(flatten_eval_results(initial_results, prefix='initial_'))

        save_summary(summary, combine_eval_records(eval_results))
        return summary

    finally:
        cleanup_model(model)

In [17]:
def build_run_plan():
    return [
        {
            'rank': x['rank'],
            'component': x['component'],
        }
        for x in MANUAL_RUNS
    ]


RUN_PLAN = build_run_plan()

print('Training corpus:', METAMATH_TRAIN_DATASET_ID)
print('Evaluation tasks:', EVAL_TASKS)
print('PiSSA runs:', len(RUN_PLAN))
for x in RUN_PLAN[:20]:
    print(x)
if len(RUN_PLAN) > 20:
    print('...')

Training corpus: meta-math/MetaMathQA
Evaluation tasks: ['gsm8k', 'math']
PiSSA runs: 0

In [18]:
ALL_RESULTS = []

if RUN_FRESH_BASELINE:
    try:
        ALL_RESULTS.append(run_fresh_baseline())
        save_master_results(ALL_RESULTS)
    except Exception as exc:
        error_row = {
            'run_tag': safe_run_tag('fresh'),
            'training_dataset': METAMATH_TRAIN_DATASET_ID,
            'method': 'fresh',
            'rank': None,
            'component': None,
            'status': 'error',
            'error': repr(exc),
        }
        ALL_RESULTS.append(error_row)
        save_master_results(ALL_RESULTS)
        print('Fresh baseline failed:', error_row)

for spec in RUN_PLAN:
    try:
        row = run_pissa_experiment(**spec)
        ALL_RESULTS.append(row)
    except torch.cuda.OutOfMemoryError as exc:
        row = {
            **spec,
            'training_dataset': METAMATH_TRAIN_DATASET_ID,
            'method': 'pissa',
            'run_tag': safe_run_tag('pissa', spec['rank'], spec['component']),
            'status': 'oom',
            'error': repr(exc),
        }
        ALL_RESULTS.append(row)
        print('OOM recorded; continuing:', row['run_tag'])
        gc.collect()
        torch.cuda.empty_cache()
    except Exception as exc:
        row = {
            **spec,
            'training_dataset': METAMATH_TRAIN_DATASET_ID,
            'method': 'pissa',
            'run_tag': safe_run_tag('pissa', spec['rank'], spec['component']),
            'status': 'error',
            'error': repr(exc),
        }
        ALL_RESULTS.append(row)
        print('Error recorded; continuing:', row)
    finally:
        save_master_results(ALL_RESULTS)

RESULTS_DF = save_master_results(ALL_RESULTS)
RESULTS_DF

================================================================================
FRESH BASELINE: evaluate GSM8K + MATH
================================================================================

Eval gsm8k:   0%|          | 0/250 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Eval gsm8k:   0%|          | 1/250 [00:06<27:49,  6.70s/it]

Eval gsm8k:   1%|          | 2/250 [00:12<25:59,  6.29s/it]

Eval gsm8k:   1%|          | 3/250 [00:18<25:25,  6.18s/it]

Eval gsm8k:   2%|▏         | 4/250 [00:24<25:00,  6.10s/it]

Eval gsm8k:   2%|▏         | 5/250 [00:30<24:41,  6.05s/it]

Eval gsm8k:   2%|▏         | 6/250 [00:36<24:34,  6.04s/it]

Eval gsm8k:   3%|▎         | 7/250 [00:42<24:39,  6.09s/it]

Eval gsm8k:   3%|▎         | 8/250 [00:48<24:22,  6.04s/it]

Eval gsm8k:   4%|▎         | 9/250 [00:54<24:10,  6.02s/it]

Eval gsm8k:   4%|▍         | 10/250 [01:00<24:13,  6.06s/it]

Eval gsm8k:   4%|▍         | 11/250 [01:06<24:02,  6.03s/it]

Eval gsm8k:   5%|▍         | 12/250 [01:13<24:13,  6.11s/it]

Eval gsm8k:   5%|▌         | 13/250 [01:19<24:07,  6.11s/it]

Eval gsm8k:   6%|▌         | 14/250 [01:25<24:22,  6.20s/it]

Eval gsm8k:   6%|▌         | 15/250 [01:31<24:10,  6.17s/it]

Eval gsm8k:   6%|▋         | 16/250 [01:37<23:49,  6.11s/it]

Eval gsm8k:   7%|▋         | 17/250 [01:43<23:35,  6.08s/it]

Eval gsm8k:   7%|▋         | 18/250 [01:49<23:19,  6.03s/it]

Eval gsm8k:   8%|▊         | 19/250 [01:55<23:09,  6.02s/it]

Eval gsm8k:   8%|▊         | 20/250 [02:01<22:59,  6.00s/it]

Eval gsm8k:   8%|▊         | 21/250 [02:07<22:50,  5.99s/it]

Eval gsm8k:   9%|▉         | 22/250 [02:13<22:50,  6.01s/it]

Eval gsm8k:   9%|▉         | 23/250 [02:19<22:41,  6.00s/it]

Eval gsm8k:  10%|▉         | 24/250 [02:25<22:33,  5.99s/it]

Eval gsm8k:  10%|█         | 25/250 [02:31<22:26,  5.98s/it]

Eval gsm8k:  10%|█         | 26/250 [02:37<22:35,  6.05s/it]

Eval gsm8k:  11%|█         | 27/250 [02:43<22:28,  6.05s/it]

Eval gsm8k:  11%|█         | 28/250 [02:50<22:29,  6.08s/it]

Eval gsm8k:  12%|█▏        | 29/250 [02:55<22:18,  6.06s/it]

Eval gsm8k:  12%|█▏        | 30/250 [03:01<22:06,  6.03s/it]

Eval gsm8k:  12%|█▏        | 31/250 [03:07<21:58,  6.02s/it]

Eval gsm8k:  13%|█▎        | 32/250 [03:13<21:51,  6.02s/it]

Eval gsm8k:  13%|█▎        | 33/250 [03:20<21:51,  6.05s/it]

Eval gsm8k:  14%|█▎        | 34/250 [03:26<21:38,  6.01s/it]

Eval gsm8k:  14%|█▍        | 35/250 [03:32<21:37,  6.03s/it]

Eval gsm8k:  14%|█▍        | 36/250 [03:38<21:23,  6.00s/it]

Eval gsm8k:  15%|█▍        | 37/250 [03:44<21:19,  6.01s/it]

Eval gsm8k:  15%|█▌        | 38/250 [03:50<21:14,  6.01s/it]

Eval gsm8k:  16%|█▌        | 39/250 [03:56<21:07,  6.01s/it]

Eval gsm8k:  16%|█▌        | 40/250 [04:02<21:08,  6.04s/it]

Eval gsm8k:  16%|█▋        | 41/250 [04:08<20:57,  6.02s/it]

Eval gsm8k:  17%|█▋        | 42/250 [04:14<20:55,  6.04s/it]

Eval gsm8k:  17%|█▋        | 43/250 [04:20<20:41,  6.00s/it]

Eval gsm8k:  18%|█▊        | 44/250 [04:26<20:37,  6.01s/it]

Eval gsm8k:  18%|█▊        | 45/250 [04:32<20:55,  6.12s/it]

Eval gsm8k:  18%|█▊        | 46/250 [04:38<20:45,  6.10s/it]

Eval gsm8k:  19%|█▉        | 47/250 [04:44<20:34,  6.08s/it]

Eval gsm8k:  19%|█▉        | 48/250 [04:50<20:15,  6.02s/it]

Eval gsm8k:  20%|█▉        | 49/250 [04:56<20:11,  6.03s/it]

Eval gsm8k:  20%|██        | 50/250 [05:02<20:07,  6.04s/it]

Eval gsm8k:  20%|██        | 51/250 [05:08<20:02,  6.04s/it]

Eval gsm8k:  21%|██        | 52/250 [05:14<19:56,  6.05s/it]

Eval gsm8k:  21%|██        | 53/250 [05:20<19:53,  6.06s/it]

Eval gsm8k:  22%|██▏       | 54/250 [05:26<19:40,  6.02s/it]

Eval gsm8k:  22%|██▏       | 55/250 [05:32<19:27,  5.99s/it]

Eval gsm8k:  22%|██▏       | 56/250 [05:38<19:19,  5.98s/it]

Eval gsm8k:  23%|██▎       | 57/250 [05:44<19:17,  6.00s/it]

Eval gsm8k:  23%|██▎       | 58/250 [05:50<19:17,  6.03s/it]

Eval gsm8k:  24%|██▎       | 59/250 [05:56<19:10,  6.03s/it]

Eval gsm8k:  24%|██▍       | 60/250 [06:02<19:05,  6.03s/it]

Eval gsm8k:  24%|██▍       | 61/250 [06:08<19:06,  6.07s/it]

Eval gsm8k:  25%|██▍       | 62/250 [06:14<18:53,  6.03s/it]

Eval gsm8k:  25%|██▌       | 63/250 [06:20<18:40,  5.99s/it]

Eval gsm8k:  26%|██▌       | 64/250 [06:26<18:35,  5.99s/it]

Eval gsm8k:  26%|██▌       | 65/250 [06:32<18:34,  6.02s/it]

Eval gsm8k:  26%|██▋       | 66/250 [06:39<18:32,  6.05s/it]

Eval gsm8k:  27%|██▋       | 67/250 [06:45<18:30,  6.07s/it]

Eval gsm8k:  27%|██▋       | 68/250 [06:51<18:20,  6.05s/it]

Eval gsm8k:  28%|██▊       | 69/250 [06:57<18:11,  6.03s/it]

Eval gsm8k:  28%|██▊       | 70/250 [07:03<18:03,  6.02s/it]

Eval gsm8k:  28%|██▊       | 71/250 [07:09<17:55,  6.01s/it]

Eval gsm8k:  29%|██▉       | 72/250 [07:15<17:46,  5.99s/it]

Eval gsm8k:  29%|██▉       | 73/250 [07:21<17:48,  6.03s/it]

Eval gsm8k:  30%|██▉       | 74/250 [07:27<17:46,  6.06s/it]

Eval gsm8k:  30%|███       | 75/250 [07:33<17:34,  6.03s/it]

Eval gsm8k:  30%|███       | 76/250 [07:39<17:30,  6.04s/it]

Eval gsm8k:  31%|███       | 77/250 [07:45<17:34,  6.09s/it]

Eval gsm8k:  31%|███       | 78/250 [07:51<17:30,  6.11s/it]

Eval gsm8k:  32%|███▏      | 79/250 [07:57<17:13,  6.04s/it]

Eval gsm8k:  32%|███▏      | 80/250 [08:03<17:01,  6.01s/it]

Eval gsm8k:  32%|███▏      | 81/250 [08:09<16:53,  6.00s/it]

Eval gsm8k:  33%|███▎      | 82/250 [08:15<16:43,  5.97s/it]

Eval gsm8k:  33%|███▎      | 83/250 [08:21<16:35,  5.96s/it]

Eval gsm8k:  34%|███▎      | 84/250 [08:27<16:28,  5.95s/it]

Eval gsm8k:  34%|███▍      | 85/250 [08:33<16:20,  5.94s/it]

Eval gsm8k:  34%|███▍      | 86/250 [08:39<16:17,  5.96s/it]

Eval gsm8k:  35%|███▍      | 87/250 [08:45<16:14,  5.98s/it]

Eval gsm8k:  35%|███▌      | 88/250 [08:51<16:12,  6.00s/it]

Eval gsm8k:  36%|███▌      | 89/250 [08:57<16:10,  6.03s/it]

Eval gsm8k:  36%|███▌      | 90/250 [09:03<16:03,  6.02s/it]

Eval gsm8k:  36%|███▋      | 91/250 [09:09<16:02,  6.05s/it]

Eval gsm8k:  37%|███▋      | 92/250 [09:15<16:01,  6.09s/it]

Eval gsm8k:  37%|███▋      | 93/250 [09:21<15:59,  6.11s/it]

Eval gsm8k:  38%|███▊      | 94/250 [09:27<15:49,  6.08s/it]

Eval gsm8k:  38%|███▊      | 95/250 [09:33<15:36,  6.04s/it]

Eval gsm8k:  38%|███▊      | 96/250 [09:39<15:31,  6.05s/it]

Eval gsm8k:  39%|███▉      | 97/250 [09:45<15:26,  6.05s/it]

Eval gsm8k:  39%|███▉      | 98/250 [09:51<15:14,  6.02s/it]

Eval gsm8k:  40%|███▉      | 99/250 [09:57<15:11,  6.04s/it]

Eval gsm8k:  40%|████      | 100/250 [10:03<15:02,  6.02s/it]

Eval gsm8k:  40%|████      | 101/250 [10:09<14:56,  6.02s/it]

Eval gsm8k:  41%|████      | 102/250 [10:15<14:50,  6.02s/it]

Eval gsm8k:  41%|████      | 103/250 [10:21<14:47,  6.04s/it]

Eval gsm8k:  42%|████▏     | 104/250 [10:27<14:38,  6.02s/it]

Eval gsm8k:  42%|████▏     | 105/250 [10:33<14:31,  6.01s/it]

Eval gsm8k:  42%|████▏     | 106/250 [10:40<14:29,  6.04s/it]

Eval gsm8k:  43%|████▎     | 107/250 [10:46<14:23,  6.04s/it]

Eval gsm8k:  43%|████▎     | 108/250 [10:52<14:20,  6.06s/it]

Eval gsm8k:  44%|████▎     | 109/250 [10:58<14:20,  6.10s/it]

Eval gsm8k:  44%|████▍     | 110/250 [11:04<14:14,  6.10s/it]

Eval gsm8k:  44%|████▍     | 111/250 [11:10<14:01,  6.06s/it]

Eval gsm8k:  45%|████▍     | 112/250 [11:16<13:52,  6.03s/it]

Eval gsm8k:  45%|████▌     | 113/250 [11:22<13:42,  6.00s/it]

Eval gsm8k:  46%|████▌     | 114/250 [11:28<13:33,  5.98s/it]

Eval gsm8k:  46%|████▌     | 115/250 [11:34<13:28,  5.99s/it]

Eval gsm8k:  46%|████▋     | 116/250 [11:40<13:23,  5.99s/it]

Eval gsm8k:  47%|████▋     | 117/250 [11:46<13:14,  5.97s/it]

Eval gsm8k:  47%|████▋     | 118/250 [11:52<13:06,  5.96s/it]

Eval gsm8k:  48%|████▊     | 119/250 [11:58<12:59,  5.95s/it]

Eval gsm8k:  48%|████▊     | 120/250 [12:04<12:57,  5.98s/it]

Eval gsm8k:  48%|████▊     | 121/250 [12:10<13:01,  6.06s/it]

Eval gsm8k:  49%|████▉     | 122/250 [12:16<12:51,  6.03s/it]

Eval gsm8k:  49%|████▉     | 123/250 [12:22<12:49,  6.06s/it]

Eval gsm8k:  50%|████▉     | 124/250 [12:28<12:40,  6.04s/it]

Eval gsm8k:  50%|█████     | 125/250 [12:34<12:31,  6.01s/it]

Eval gsm8k:  50%|█████     | 126/250 [12:40<12:22,  5.98s/it]

Eval gsm8k:  51%|█████     | 127/250 [12:46<12:15,  5.98s/it]

Eval gsm8k:  51%|█████     | 128/250 [12:52<12:12,  6.01s/it]

Eval gsm8k:  52%|█████▏    | 129/250 [12:58<12:02,  5.97s/it]

Eval gsm8k:  52%|█████▏    | 130/250 [13:04<11:55,  5.97s/it]

Eval gsm8k:  52%|█████▏    | 131/250 [13:10<11:55,  6.01s/it]

Eval gsm8k:  53%|█████▎    | 132/250 [13:16<11:47,  5.99s/it]

Eval gsm8k:  53%|█████▎    | 133/250 [13:22<11:38,  5.97s/it]

Eval gsm8k:  54%|█████▎    | 134/250 [13:28<11:34,  5.98s/it]

Eval gsm8k:  54%|█████▍    | 135/250 [13:34<11:26,  5.97s/it]

Eval gsm8k:  54%|█████▍    | 136/250 [13:40<11:23,  5.99s/it]

Eval gsm8k:  55%|█████▍    | 137/250 [13:46<11:17,  5.99s/it]

Eval gsm8k:  55%|█████▌    | 138/250 [13:52<11:14,  6.03s/it]

Eval gsm8k:  56%|█████▌    | 139/250 [13:58<11:05,  6.00s/it]

Eval gsm8k:  56%|█████▌    | 140/250 [14:04<11:03,  6.03s/it]

Eval gsm8k:  56%|█████▋    | 141/250 [14:10<10:57,  6.03s/it]

Eval gsm8k:  57%|█████▋    | 142/250 [14:16<10:49,  6.01s/it]

Eval gsm8k:  57%|█████▋    | 143/250 [14:22<10:44,  6.02s/it]

Eval gsm8k:  58%|█████▊    | 144/250 [14:28<10:37,  6.01s/it]

Eval gsm8k:  58%|█████▊    | 145/250 [14:34<10:32,  6.02s/it]

Eval gsm8k:  58%|█████▊    | 146/250 [14:40<10:23,  5.99s/it]

Eval gsm8k:  59%|█████▉    | 147/250 [14:46<10:15,  5.98s/it]

Eval gsm8k:  59%|█████▉    | 148/250 [14:52<10:10,  5.98s/it]

Eval gsm8k:  60%|█████▉    | 149/250 [14:58<10:02,  5.96s/it]

Eval gsm8k:  60%|██████    | 150/250 [15:04<10:00,  6.01s/it]

Eval gsm8k:  60%|██████    | 151/250 [15:10<09:57,  6.03s/it]

Eval gsm8k:  61%|██████    | 152/250 [15:16<09:51,  6.03s/it]

Eval gsm8k:  61%|██████    | 153/250 [15:22<09:46,  6.04s/it]

Eval gsm8k:  62%|██████▏   | 154/250 [15:28<09:39,  6.04s/it]

Eval gsm8k:  62%|██████▏   | 155/250 [15:34<09:32,  6.02s/it]

Eval gsm8k:  62%|██████▏   | 156/250 [15:40<09:25,  6.01s/it]

Eval gsm8k:  63%|██████▎   | 157/250 [15:46<09:16,  5.98s/it]

Eval gsm8k:  63%|██████▎   | 158/250 [15:52<09:08,  5.96s/it]

Eval gsm8k:  64%|██████▎   | 159/250 [15:58<09:05,  5.99s/it]

Eval gsm8k:  64%|██████▍   | 160/250 [16:04<09:03,  6.04s/it]

Eval gsm8k:  64%|██████▍   | 161/250 [16:10<08:56,  6.03s/it]

Eval gsm8k:  65%|██████▍   | 162/250 [16:16<08:47,  5.99s/it]

Eval gsm8k:  65%|██████▌   | 163/250 [16:22<08:41,  5.99s/it]

Eval gsm8k:  66%|██████▌   | 164/250 [16:28<08:36,  6.00s/it]

Eval gsm8k:  66%|██████▌   | 165/250 [16:34<08:32,  6.03s/it]

Eval gsm8k:  66%|██████▋   | 166/250 [16:40<08:28,  6.05s/it]

Eval gsm8k:  67%|██████▋   | 167/250 [16:46<08:19,  6.02s/it]

Eval gsm8k:  67%|██████▋   | 168/250 [16:52<08:12,  6.01s/it]

Eval gsm8k:  68%|██████▊   | 169/250 [16:58<08:05,  5.99s/it]

Eval gsm8k:  68%|██████▊   | 170/250 [17:04<07:59,  6.00s/it]

Eval gsm8k:  68%|██████▊   | 171/250 [17:10<07:59,  6.07s/it]

Eval gsm8k:  69%|██████▉   | 172/250 [17:16<07:53,  6.07s/it]

Eval gsm8k:  69%|██████▉   | 173/250 [17:22<07:43,  6.02s/it]

Eval gsm8k:  70%|██████▉   | 174/250 [17:28<07:36,  6.00s/it]

Eval gsm8k:  70%|███████   | 175/250 [17:34<07:31,  6.03s/it]

Eval gsm8k:  70%|███████   | 176/250 [17:40<07:26,  6.04s/it]

Eval gsm8k:  71%|███████   | 177/250 [17:46<07:18,  6.01s/it]

Eval gsm8k:  71%|███████   | 178/250 [17:52<07:11,  6.00s/it]

Eval gsm8k:  72%|███████▏  | 179/250 [17:58<07:07,  6.02s/it]

Eval gsm8k:  72%|███████▏  | 180/250 [18:04<07:02,  6.03s/it]

Eval gsm8k:  72%|███████▏  | 181/250 [18:11<06:58,  6.06s/it]

Eval gsm8k:  73%|███████▎  | 182/250 [18:17<06:52,  6.07s/it]

Eval gsm8k:  73%|███████▎  | 183/250 [18:23<06:44,  6.03s/it]

Eval gsm8k:  74%|███████▎  | 184/250 [18:29<06:37,  6.02s/it]

Eval gsm8k:  74%|███████▍  | 185/250 [18:35<06:31,  6.03s/it]

Eval gsm8k:  74%|███████▍  | 186/250 [18:41<06:23,  6.00s/it]

Eval gsm8k:  75%|███████▍  | 187/250 [18:47<06:18,  6.01s/it]

Eval gsm8k:  75%|███████▌  | 188/250 [18:53<06:14,  6.04s/it]

Eval gsm8k:  76%|███████▌  | 189/250 [18:59<06:10,  6.07s/it]

Eval gsm8k:  76%|███████▌  | 190/250 [19:05<06:04,  6.07s/it]

Eval gsm8k:  76%|███████▋  | 191/250 [19:11<05:55,  6.03s/it]

Eval gsm8k:  77%|███████▋  | 192/250 [19:17<05:50,  6.05s/it]

Eval gsm8k:  77%|███████▋  | 193/250 [19:23<05:43,  6.03s/it]

Eval gsm8k:  78%|███████▊  | 194/250 [19:29<05:37,  6.03s/it]

Eval gsm8k:  78%|███████▊  | 195/250 [19:35<05:30,  6.01s/it]

Eval gsm8k:  78%|███████▊  | 196/250 [19:41<05:24,  6.01s/it]

Eval gsm8k:  79%|███████▉  | 197/250 [19:47<05:17,  5.99s/it]

Eval gsm8k:  79%|███████▉  | 198/250 [19:53<05:11,  5.99s/it]

Eval gsm8k:  80%|███████▉  | 199/250 [19:59<05:07,  6.02s/it]

Eval gsm8k:  80%|████████  | 200/250 [20:05<05:00,  6.01s/it]

Eval gsm8k:  80%|████████  | 201/250 [20:11<04:53,  5.99s/it]

Eval gsm8k:  81%|████████  | 202/250 [20:17<04:49,  6.04s/it]

Eval gsm8k:  81%|████████  | 203/250 [20:23<04:42,  6.01s/it]

Eval gsm8k:  82%|████████▏ | 204/250 [20:29<04:35,  6.00s/it]

Eval gsm8k:  82%|████████▏ | 205/250 [20:35<04:28,  5.97s/it]

Eval gsm8k:  82%|████████▏ | 206/250 [20:41<04:23,  5.98s/it]

Eval gsm8k:  83%|████████▎ | 207/250 [20:47<04:16,  5.97s/it]

Eval gsm8k:  83%|████████▎ | 208/250 [20:53<04:10,  5.97s/it]

Eval gsm8k:  84%|████████▎ | 209/250 [20:59<04:04,  5.96s/it]

Eval gsm8k:  84%|████████▍ | 210/250 [21:05<03:58,  5.97s/it]

Eval gsm8k:  84%|████████▍ | 211/250 [21:11<03:52,  5.95s/it]

Eval gsm8k:  85%|████████▍ | 212/250 [21:17<03:47,  5.99s/it]

Eval gsm8k:  85%|████████▌ | 213/250 [21:23<03:40,  5.97s/it]

Eval gsm8k:  86%|████████▌ | 214/250 [21:29<03:34,  5.97s/it]

Eval gsm8k:  86%|████████▌ | 215/250 [21:35<03:30,  6.02s/it]

Eval gsm8k:  86%|████████▋ | 216/250 [21:41<03:23,  5.99s/it]

Eval gsm8k:  87%|████████▋ | 217/250 [21:47<03:17,  5.98s/it]

Eval gsm8k:  87%|████████▋ | 218/250 [21:53<03:11,  5.98s/it]

Eval gsm8k:  88%|████████▊ | 219/250 [21:58<03:04,  5.95s/it]

Eval gsm8k:  88%|████████▊ | 220/250 [22:04<02:58,  5.96s/it]

Eval gsm8k:  88%|████████▊ | 221/250 [22:10<02:53,  5.97s/it]

Eval gsm8k:  89%|████████▉ | 222/250 [22:17<02:48,  6.01s/it]

Eval gsm8k:  89%|████████▉ | 223/250 [22:23<02:42,  6.03s/it]

Eval gsm8k:  90%|████████▉ | 224/250 [22:29<02:36,  6.00s/it]

Eval gsm8k:  90%|█████████ | 225/250 [22:35<02:30,  6.03s/it]

Eval gsm8k:  90%|█████████ | 226/250 [22:41<02:24,  6.02s/it]

Eval gsm8k:  91%|█████████ | 227/250 [22:47<02:17,  5.98s/it]

Eval gsm8k:  91%|█████████ | 228/250 [22:53<02:13,  6.05s/it]

Eval gsm8k:  92%|█████████▏| 229/250 [22:59<02:06,  6.03s/it]

Eval gsm8k:  92%|█████████▏| 230/250 [23:05<02:01,  6.06s/it]

Eval gsm8k:  92%|█████████▏| 231/250 [23:11<01:55,  6.07s/it]

Eval gsm8k:  93%|█████████▎| 232/250 [23:17<01:48,  6.05s/it]

Eval gsm8k:  93%|█████████▎| 233/250 [23:23<01:42,  6.05s/it]

Eval gsm8k:  94%|█████████▎| 234/250 [23:29<01:37,  6.08s/it]

Eval gsm8k:  94%|█████████▍| 235/250 [23:35<01:30,  6.05s/it]

Eval gsm8k:  94%|█████████▍| 236/250 [23:41<01:24,  6.05s/it]

Eval gsm8k:  95%|█████████▍| 237/250 [23:47<01:18,  6.03s/it]

Eval gsm8k:  95%|█████████▌| 238/250 [23:53<01:12,  6.02s/it]

Eval gsm8k:  96%|█████████▌| 239/250 [23:59<01:06,  6.02s/it]

Eval gsm8k:  96%|█████████▌| 240/250 [24:05<01:00,  6.03s/it]

Eval gsm8k:  96%|█████████▋| 241/250 [24:11<00:54,  6.05s/it]

Eval gsm8k:  97%|█████████▋| 242/250 [24:17<00:48,  6.04s/it]

Eval gsm8k:  97%|█████████▋| 243/250 [24:23<00:42,  6.05s/it]

Eval gsm8k:  98%|█████████▊| 244/250 [24:30<00:36,  6.07s/it]

Eval gsm8k:  98%|█████████▊| 245/250 [24:36<00:30,  6.04s/it]

Eval gsm8k:  98%|█████████▊| 246/250 [24:41<00:24,  6.01s/it]

Eval gsm8k:  99%|█████████▉| 247/250 [24:48<00:18,  6.04s/it]

Eval gsm8k:  99%|█████████▉| 248/250 [24:54<00:12,  6.05s/it]

Eval gsm8k: 100%|█████████▉| 249/250 [25:00<00:06,  6.03s/it]

Eval gsm8k: 100%|██████████| 250/250 [25:06<00:00,  6.00s/it]

Eval gsm8k: 100%|██████████| 250/250 [25:06<00:00,  6.02s/it]

Eval math:   0%|          | 0/250 [00:00<?, ?it/s]

Eval math:   0%|          | 1/250 [00:05<24:46,  5.97s/it]

Eval math:   1%|          | 2/250 [00:12<24:56,  6.04s/it]

Eval math:   1%|          | 3/250 [00:18<24:52,  6.04s/it]

Eval math:   2%|▏         | 4/250 [00:24<24:50,  6.06s/it]

Eval math:   2%|▏         | 5/250 [00:30<25:14,  6.18s/it]

Eval math:   2%|▏         | 6/250 [00:36<24:58,  6.14s/it]

Eval math:   3%|▎         | 7/250 [00:42<24:47,  6.12s/it]

Eval math:   3%|▎         | 8/250 [00:48<24:39,  6.11s/it]

Eval math:   4%|▎         | 9/250 [00:54<24:33,  6.11s/it]

Eval math:   4%|▍         | 10/250 [01:01<24:29,  6.12s/it]

Eval math:   4%|▍         | 11/250 [01:07<24:24,  6.13s/it]

Eval math:   5%|▍         | 12/250 [01:13<24:13,  6.11s/it]

Eval math:   5%|▌         | 13/250 [01:19<24:05,  6.10s/it]

Eval math:   6%|▌         | 14/250 [01:25<23:56,  6.09s/it]

Eval math:   6%|▌         | 15/250 [01:31<24:06,  6.15s/it]

Eval math:   6%|▋         | 16/250 [01:37<23:49,  6.11s/it]

Eval math:   7%|▋         | 17/250 [01:43<23:47,  6.13s/it]

Eval math:   7%|▋         | 18/250 [01:50<23:46,  6.15s/it]

Eval math:   8%|▊         | 19/250 [01:56<23:29,  6.10s/it]

Eval math:   8%|▊         | 20/250 [02:02<23:22,  6.10s/it]

Eval math:   8%|▊         | 21/250 [02:08<23:13,  6.09s/it]

Eval math:   9%|▉         | 22/250 [02:14<23:14,  6.12s/it]

Eval math:   9%|▉         | 23/250 [02:20<22:52,  6.05s/it]

Eval math:  10%|▉         | 24/250 [02:26<22:42,  6.03s/it]

Eval math:  10%|█         | 25/250 [02:32<22:40,  6.05s/it]

Eval math:  10%|█         | 26/250 [02:37<22:00,  5.89s/it]

Eval math:  11%|█         | 27/250 [02:43<21:58,  5.91s/it]

Eval math:  11%|█         | 28/250 [02:49<21:53,  5.92s/it]

Eval math:  12%|█▏        | 29/250 [02:55<22:01,  5.98s/it]

Eval math:  12%|█▏        | 30/250 [03:01<21:55,  5.98s/it]

Eval math:  12%|█▏        | 31/250 [03:07<21:48,  5.98s/it]

Eval math:  13%|█▎        | 32/250 [03:14<21:53,  6.02s/it]

Eval math:  13%|█▎        | 33/250 [03:20<21:52,  6.05s/it]

Eval math:  14%|█▎        | 34/250 [03:26<21:39,  6.02s/it]

Eval math:  14%|█▍        | 35/250 [03:32<21:32,  6.01s/it]

Eval math:  14%|█▍        | 36/250 [03:38<21:24,  6.00s/it]

Eval math:  15%|█▍        | 37/250 [03:44<21:22,  6.02s/it]

Eval math:  15%|█▌        | 38/250 [03:50<21:21,  6.04s/it]

Eval math:  16%|█▌        | 39/250 [03:56<21:18,  6.06s/it]

Eval math:  16%|█▌        | 40/250 [04:02<21:06,  6.03s/it]

Eval math:  16%|█▋        | 41/250 [04:08<20:56,  6.01s/it]

Eval math:  17%|█▋        | 42/250 [04:14<20:49,  6.01s/it]

Eval math:  17%|█▋        | 43/250 [04:20<20:50,  6.04s/it]

Eval math:  18%|█▊        | 44/250 [04:26<20:37,  6.01s/it]

Eval math:  18%|█▊        | 45/250 [04:32<21:02,  6.16s/it]

Eval math:  18%|█▊        | 46/250 [04:39<21:01,  6.18s/it]

Eval math:  19%|█▉        | 47/250 [04:45<20:48,  6.15s/it]

Eval math:  19%|█▉        | 48/250 [04:51<20:30,  6.09s/it]

Eval math:  20%|█▉        | 49/250 [04:57<20:23,  6.09s/it]

Eval math:  20%|██        | 50/250 [05:03<20:18,  6.09s/it]

Eval math:  20%|██        | 51/250 [05:09<20:04,  6.05s/it]

Eval math:  21%|██        | 52/250 [05:15<19:53,  6.03s/it]

Eval math:  21%|██        | 53/250 [05:21<19:50,  6.04s/it]

Eval math:  22%|██▏       | 54/250 [05:27<19:39,  6.02s/it]

Eval math:  22%|██▏       | 55/250 [05:33<19:36,  6.03s/it]

Eval math:  22%|██▏       | 56/250 [05:39<19:31,  6.04s/it]

Eval math:  23%|██▎       | 57/250 [05:45<19:25,  6.04s/it]

Eval math:  23%|██▎       | 58/250 [05:51<19:18,  6.03s/it]

Eval math:  24%|██▎       | 59/250 [05:57<19:15,  6.05s/it]

Eval math:  24%|██▍       | 60/250 [06:03<19:10,  6.06s/it]

Eval math:  24%|██▍       | 61/250 [06:09<19:00,  6.03s/it]

Eval math:  25%|██▍       | 62/250 [06:15<18:50,  6.01s/it]

Eval math:  25%|██▌       | 63/250 [06:21<18:55,  6.07s/it]

Eval math:  26%|██▌       | 64/250 [06:27<18:54,  6.10s/it]

Eval math:  26%|██▌       | 65/250 [06:33<18:47,  6.09s/it]

Eval math:  26%|██▋       | 66/250 [06:39<18:37,  6.07s/it]

Eval math:  27%|██▋       | 67/250 [06:46<18:33,  6.09s/it]

Eval math:  27%|██▋       | 68/250 [06:52<18:36,  6.14s/it]

Eval math:  28%|██▊       | 69/250 [06:58<18:33,  6.15s/it]

Eval math:  28%|██▊       | 70/250 [07:04<18:23,  6.13s/it]

Eval math:  28%|██▊       | 71/250 [07:10<18:12,  6.11s/it]

Eval math:  29%|██▉       | 72/250 [07:16<18:10,  6.13s/it]

Eval math:  29%|██▉       | 73/250 [07:23<18:07,  6.14s/it]

Eval math:  30%|██▉       | 74/250 [07:28<17:51,  6.09s/it]

Eval math:  30%|███       | 75/250 [07:35<17:53,  6.13s/it]

Eval math:  30%|███       | 76/250 [07:41<17:53,  6.17s/it]

Eval math:  31%|███       | 77/250 [07:47<17:48,  6.18s/it]

Eval math:  31%|███       | 78/250 [07:53<17:47,  6.21s/it]

Eval math:  32%|███▏      | 79/250 [08:00<17:37,  6.18s/it]

Eval math:  32%|███▏      | 80/250 [08:06<17:21,  6.13s/it]

Eval math:  32%|███▏      | 81/250 [08:12<17:10,  6.10s/it]

Eval math:  33%|███▎      | 82/250 [08:18<16:59,  6.07s/it]

Eval math:  33%|███▎      | 83/250 [08:24<16:55,  6.08s/it]

Eval math:  34%|███▎      | 84/250 [08:30<16:53,  6.10s/it]

Eval math:  34%|███▍      | 85/250 [08:36<16:53,  6.14s/it]

Eval math:  34%|███▍      | 86/250 [08:42<16:43,  6.12s/it]

Eval math:  35%|███▍      | 87/250 [08:48<16:32,  6.09s/it]

Eval math:  35%|███▌      | 88/250 [08:54<16:27,  6.10s/it]

Eval math:  36%|███▌      | 89/250 [09:00<16:15,  6.06s/it]

Eval math:  36%|███▌      | 90/250 [09:06<16:12,  6.08s/it]

Eval math:  36%|███▋      | 91/250 [09:13<16:09,  6.10s/it]

Eval math:  37%|███▋      | 92/250 [09:18<15:56,  6.05s/it]

Eval math:  37%|███▋      | 93/250 [09:25<15:48,  6.04s/it]

Eval math:  38%|███▊      | 94/250 [09:30<15:35,  6.00s/it]

Eval math:  38%|███▊      | 95/250 [09:36<15:33,  6.02s/it]

Eval math:  38%|███▊      | 96/250 [09:43<15:30,  6.04s/it]

Eval math:  39%|███▉      | 97/250 [09:49<15:22,  6.03s/it]

Eval math:  39%|███▉      | 98/250 [09:55<15:15,  6.02s/it]

Eval math:  40%|███▉      | 99/250 [10:01<15:06,  6.00s/it]

Eval math:  40%|████      | 100/250 [10:07<15:02,  6.02s/it]

Eval math:  40%|████      | 101/250 [10:13<14:59,  6.04s/it]

Eval math:  41%|████      | 102/250 [10:19<14:56,  6.06s/it]

Eval math:  41%|████      | 103/250 [10:25<14:52,  6.07s/it]

Eval math:  42%|████▏     | 104/250 [10:31<14:49,  6.09s/it]

Eval math:  42%|████▏     | 105/250 [10:37<14:38,  6.06s/it]

Eval math:  42%|████▏     | 106/250 [10:43<14:37,  6.09s/it]

Eval math:  43%|████▎     | 107/250 [10:49<14:25,  6.05s/it]

Eval math:  43%|████▎     | 108/250 [10:55<14:25,  6.09s/it]

Eval math:  44%|████▎     | 109/250 [11:02<14:28,  6.16s/it]

Eval math:  44%|████▍     | 110/250 [11:08<14:15,  6.11s/it]

Eval math:  44%|████▍     | 111/250 [11:14<14:10,  6.12s/it]

Eval math:  45%|████▍     | 112/250 [11:20<14:04,  6.12s/it]

Eval math:  45%|████▌     | 113/250 [11:26<13:57,  6.11s/it]

Eval math:  46%|████▌     | 114/250 [11:32<13:52,  6.12s/it]

Eval math:  46%|████▌     | 115/250 [11:38<13:46,  6.13s/it]

Eval math:  46%|████▋     | 116/250 [11:44<13:41,  6.13s/it]

Eval math:  47%|████▋     | 117/250 [11:50<13:32,  6.11s/it]

Eval math:  47%|████▋     | 118/250 [11:56<13:21,  6.07s/it]

Eval math:  48%|████▊     | 119/250 [12:02<13:10,  6.03s/it]

Eval math:  48%|████▊     | 120/250 [12:08<13:04,  6.03s/it]

Eval math:  48%|████▊     | 121/250 [12:14<12:58,  6.04s/it]

Eval math:  49%|████▉     | 122/250 [12:20<12:48,  6.01s/it]

Eval math:  49%|████▉     | 123/250 [12:26<12:45,  6.03s/it]

Eval math:  50%|████▉     | 124/250 [12:33<12:42,  6.05s/it]

Eval math:  50%|█████     | 125/250 [12:39<12:40,  6.09s/it]

Eval math:  50%|█████     | 126/250 [12:45<12:33,  6.08s/it]

Eval math:  51%|█████     | 127/250 [12:51<12:27,  6.08s/it]

Eval math:  51%|█████     | 128/250 [12:57<12:20,  6.07s/it]

Eval math:  52%|█████▏    | 129/250 [13:03<12:12,  6.06s/it]

Eval math:  52%|█████▏    | 130/250 [13:09<12:07,  6.06s/it]

Eval math:  52%|█████▏    | 131/250 [13:15<12:01,  6.07s/it]

Eval math:  53%|█████▎    | 132/250 [13:21<11:58,  6.09s/it]

Eval math:  53%|█████▎    | 133/250 [13:27<11:48,  6.05s/it]

Eval math:  54%|█████▎    | 134/250 [13:33<11:42,  6.05s/it]

Eval math:  54%|█████▍    | 135/250 [13:39<11:40,  6.09s/it]

Eval math:  54%|█████▍    | 136/250 [13:45<11:29,  6.05s/it]

Eval math:  55%|█████▍    | 137/250 [13:52<11:26,  6.08s/it]

Eval math:  55%|█████▌    | 138/250 [13:58<11:21,  6.08s/it]

Eval math:  56%|█████▌    | 139/250 [14:04<11:13,  6.07s/it]

Eval math:  56%|█████▌    | 140/250 [14:10<11:12,  6.11s/it]

Eval math:  56%|█████▋    | 141/250 [14:16<10:59,  6.05s/it]

Eval math:  57%|█████▋    | 142/250 [14:22<10:53,  6.05s/it]

Eval math:  57%|█████▋    | 143/250 [14:28<10:48,  6.06s/it]

Eval math:  58%|█████▊    | 144/250 [14:34<10:46,  6.10s/it]

Eval math:  58%|█████▊    | 145/250 [14:40<10:41,  6.11s/it]

Eval math:  58%|█████▊    | 146/250 [14:46<10:34,  6.10s/it]

Eval math:  59%|█████▉    | 147/250 [14:52<10:29,  6.11s/it]

Eval math:  59%|█████▉    | 148/250 [14:59<10:23,  6.12s/it]

Eval math:  60%|█████▉    | 149/250 [15:05<10:15,  6.10s/it]

Eval math:  60%|██████    | 150/250 [15:11<10:21,  6.22s/it]

Eval math:  60%|██████    | 151/250 [15:17<10:07,  6.13s/it]

Eval math:  61%|██████    | 152/250 [15:23<09:59,  6.12s/it]

Eval math:  61%|██████    | 153/250 [15:29<09:46,  6.05s/it]

Eval math:  62%|██████▏   | 154/250 [15:35<09:40,  6.05s/it]

Eval math:  62%|██████▏   | 155/250 [15:41<09:38,  6.09s/it]

Eval math:  62%|██████▏   | 156/250 [15:47<09:27,  6.04s/it]

Eval math:  63%|██████▎   | 157/250 [15:53<09:26,  6.09s/it]

Eval math:  63%|██████▎   | 158/250 [16:00<09:21,  6.10s/it]

Eval math:  64%|██████▎   | 159/250 [16:05<09:09,  6.04s/it]

Eval math:  64%|██████▍   | 160/250 [16:11<09:02,  6.03s/it]

Eval math:  64%|██████▍   | 161/250 [16:17<08:56,  6.03s/it]

Eval math:  65%|██████▍   | 162/250 [16:24<08:50,  6.03s/it]

Eval math:  65%|██████▌   | 163/250 [16:30<08:47,  6.06s/it]

Eval math:  66%|██████▌   | 164/250 [16:36<08:38,  6.03s/it]

Eval math:  66%|██████▌   | 165/250 [16:42<08:36,  6.08s/it]

Eval math:  66%|██████▋   | 166/250 [16:48<08:29,  6.07s/it]

Eval math:  67%|██████▋   | 167/250 [16:54<08:20,  6.03s/it]

Eval math:  67%|██████▋   | 168/250 [17:00<08:13,  6.02s/it]

Eval math:  68%|██████▊   | 169/250 [17:06<08:06,  6.01s/it]

Eval math:  68%|██████▊   | 170/250 [17:12<07:59,  6.00s/it]

Eval math:  68%|██████▊   | 171/250 [17:18<07:57,  6.04s/it]

Eval math:  69%|██████▉   | 172/250 [17:24<07:56,  6.11s/it]

Eval math:  69%|██████▉   | 173/250 [17:30<07:48,  6.09s/it]

Eval math:  70%|██████▉   | 174/250 [17:36<07:43,  6.10s/it]

Eval math:  70%|███████   | 175/250 [17:42<07:36,  6.09s/it]

Eval math:  70%|███████   | 176/250 [17:48<07:29,  6.08s/it]

Eval math:  71%|███████   | 177/250 [17:55<07:24,  6.08s/it]

Eval math:  71%|███████   | 178/250 [18:01<07:16,  6.06s/it]

Eval math:  72%|███████▏  | 179/250 [18:07<07:08,  6.04s/it]

Eval math:  72%|███████▏  | 180/250 [18:13<07:03,  6.06s/it]

Eval math:  72%|███████▏  | 181/250 [18:19<06:56,  6.04s/it]

Eval math:  73%|███████▎  | 182/250 [18:25<06:50,  6.04s/it]

Eval math:  73%|███████▎  | 183/250 [18:31<06:42,  6.01s/it]

Eval math:  74%|███████▎  | 184/250 [18:37<06:37,  6.02s/it]

Eval math:  74%|███████▍  | 185/250 [18:43<06:35,  6.09s/it]

Eval math:  74%|███████▍  | 186/250 [18:49<06:29,  6.08s/it]

Eval math:  75%|███████▍  | 187/250 [18:55<06:20,  6.03s/it]

Eval math:  75%|███████▌  | 188/250 [19:01<06:14,  6.04s/it]

Eval math:  76%|███████▌  | 189/250 [19:07<06:05,  5.99s/it]

Eval math:  76%|███████▌  | 190/250 [19:13<05:59,  5.99s/it]

Eval math:  76%|███████▋  | 191/250 [19:19<05:55,  6.02s/it]

Eval math:  77%|███████▋  | 192/250 [19:25<05:49,  6.02s/it]

Eval math:  77%|███████▋  | 193/250 [19:31<05:44,  6.04s/it]

Eval math:  78%|███████▊  | 194/250 [19:37<05:43,  6.13s/it]

Eval math:  78%|███████▊  | 195/250 [19:43<05:33,  6.06s/it]

Eval math:  78%|███████▊  | 196/250 [19:49<05:28,  6.08s/it]

Eval math:  79%|███████▉  | 197/250 [19:56<05:24,  6.12s/it]

Eval math:  79%|███████▉  | 198/250 [20:02<05:17,  6.11s/it]

Eval math:  80%|███████▉  | 199/250 [20:08<05:11,  6.11s/it]

Eval math:  80%|████████  | 200/250 [20:14<05:01,  6.03s/it]

Eval math:  80%|████████  | 201/250 [20:20<04:56,  6.06s/it]

Eval math:  81%|████████  | 202/250 [20:26<04:52,  6.10s/it]

Eval math:  81%|████████  | 203/250 [20:32<04:49,  6.16s/it]

Eval math:  82%|████████▏ | 204/250 [20:38<04:42,  6.13s/it]

Eval math:  82%|████████▏ | 205/250 [20:45<04:38,  6.19s/it]

Eval math:  82%|████████▏ | 206/250 [20:51<04:36,  6.28s/it]

Eval math:  83%|████████▎ | 207/250 [20:57<04:24,  6.16s/it]

Eval math:  83%|████████▎ | 208/250 [21:03<04:17,  6.14s/it]

Eval math:  84%|████████▎ | 209/250 [21:09<04:10,  6.11s/it]

Eval math:  84%|████████▍ | 210/250 [21:15<04:03,  6.09s/it]

Eval math:  84%|████████▍ | 211/250 [21:21<03:57,  6.09s/it]

Eval math:  85%|████████▍ | 212/250 [21:27<03:49,  6.04s/it]

Eval math:  85%|████████▌ | 213/250 [21:33<03:45,  6.08s/it]

Eval math:  86%|████████▌ | 214/250 [21:39<03:36,  6.01s/it]

Eval math:  86%|████████▌ | 215/250 [21:45<03:31,  6.03s/it]

Eval math:  86%|████████▋ | 216/250 [21:51<03:24,  6.00s/it]

Eval math:  87%|████████▋ | 217/250 [21:57<03:18,  6.02s/it]

Eval math:  87%|████████▋ | 218/250 [22:03<03:13,  6.06s/it]

Eval math:  88%|████████▊ | 219/250 [22:09<03:07,  6.06s/it]

Eval math:  88%|████████▊ | 220/250 [22:16<03:01,  6.06s/it]

Eval math:  88%|████████▊ | 221/250 [22:21<02:54,  6.03s/it]

Eval math:  89%|████████▉ | 222/250 [22:28<02:48,  6.03s/it]

Eval math:  89%|████████▉ | 223/250 [22:34<02:42,  6.04s/it]

Eval math:  90%|████████▉ | 224/250 [22:39<02:35,  5.99s/it]

Eval math:  90%|█████████ | 225/250 [22:46<02:30,  6.01s/it]

Eval math:  90%|█████████ | 226/250 [22:52<02:24,  6.02s/it]

Eval math:  91%|█████████ | 227/250 [22:57<02:17,  5.98s/it]

Eval math:  91%|█████████ | 228/250 [23:03<02:12,  6.01s/it]

Eval math:  92%|█████████▏| 229/250 [23:10<02:06,  6.01s/it]

Eval math:  92%|█████████▏| 230/250 [23:16<02:02,  6.11s/it]

Eval math:  92%|█████████▏| 231/250 [23:22<01:56,  6.13s/it]

Eval math:  93%|█████████▎| 232/250 [23:28<01:50,  6.14s/it]

Eval math:  93%|█████████▎| 233/250 [23:34<01:44,  6.14s/it]

Eval math:  94%|█████████▎| 234/250 [23:41<01:39,  6.19s/it]

Eval math:  94%|█████████▍| 235/250 [23:47<01:33,  6.21s/it]

Eval math:  94%|█████████▍| 236/250 [23:53<01:25,  6.14s/it]

Eval math:  95%|█████████▍| 237/250 [23:59<01:21,  6.25s/it]

Eval math:  95%|█████████▌| 238/250 [24:05<01:14,  6.18s/it]

Eval math:  96%|█████████▌| 239/250 [24:11<01:07,  6.15s/it]

Eval math:  96%|█████████▌| 240/250 [24:17<01:01,  6.10s/it]

Eval math:  96%|█████████▋| 241/250 [24:23<00:54,  6.06s/it]

Eval math:  97%|█████████▋| 242/250 [24:30<00:48,  6.09s/it]

Eval math:  97%|█████████▋| 243/250 [24:35<00:42,  6.03s/it]

Eval math:  98%|█████████▊| 244/250 [24:41<00:35,  6.00s/it]

Eval math:  98%|█████████▊| 245/250 [24:47<00:30,  6.03s/it]

Eval math:  98%|█████████▊| 246/250 [24:53<00:24,  6.00s/it]

Eval math:  99%|█████████▉| 247/250 [24:59<00:18,  6.00s/it]

Eval math:  99%|█████████▉| 248/250 [25:05<00:11,  5.98s/it]

Eval math: 100%|█████████▉| 249/250 [25:11<00:06,  6.00s/it]

Eval math: 100%|██████████| 250/250 [25:18<00:00,  6.04s/it]

Eval math: 100%|██████████| 250/250 [25:18<00:00,  6.07s/it]

,run_tag,training_dataset,training_examples,method,rank,component,gsm8k_accuracy,gsm8k_correct,gsm8k_total,gsm8k_unparsed,gsm8k_eval_seconds,math_accuracy,math_correct,math_total,math_unparsed,math_eval_seconds,init_seconds,trainable_parameters,status,seed
0,metamath_fresh,meta-math/MetaMathQA,0,fresh,None,None,0.033,33,1000,16,1506.048535,0.001,1,1000,958,1518.049608,0.0,0,ok,42

In [19]:
if len(ALL_RESULTS):
    if 'status' in RESULTS_DF.columns:
        ok = RESULTS_DF[RESULTS_DF['status'].eq('ok')].copy()
    else:
        ok = RESULTS_DF.copy()

    display_cols = [
        c for c in [
            'method', 'rank', 'component',
            'gsm8k_accuracy', 'math_accuracy',
            'gsm8k_correct', 'gsm8k_total',
            'math_correct', 'math_total',
            'train_minutes', 'init_seconds',
            'trainable_parameters',
            'gsm8k_unparsed', 'math_unparsed',
        ] if c in ok.columns
    ]
    if len(ok):
        display(
            ok[display_cols].sort_values(
                ['method', 'rank', 'component'],
                na_position='first',
            )
        )

    required = {
        'method', 'rank', 'component',
        'gsm8k_accuracy', 'math_accuracy',
    }
    if required.issubset(ok.columns):
        pissa_only = ok[ok['method'].eq('pissa')].copy()
        if len(pissa_only):
            pivot = pissa_only.pivot_table(
                index='rank',
                columns='component',
                values=['gsm8k_accuracy', 'math_accuracy'],
                aggfunc='first',
            )
            display(pivot)

,method,rank,component,gsm8k_accuracy,math_accuracy,gsm8k_correct,gsm8k_total,math_correct,math_total,init_seconds,trainable_parameters,gsm8k_unparsed,math_unparsed
0,fresh,None,None,0.033,0.001,33,1000,1,1000,0.0,0,16,958